import type { InsertOpts } from "./insert-opts.js";

// Job states matching the River database enum.
export const JOB_STATE_AVAILABLE = "available" as const;
export const JOB_STATE_CANCELLED = "cancelled" as const;
export const JOB_STATE_COMPLETED = "completed" as const;
export const JOB_STATE_DISCARDED = "discarded" as const;
export const JOB_STATE_PENDING = "pending" as const;
export const JOB_STATE_RETRYABLE = "retryable" as const;
export const JOB_STATE_RUNNING = "running" as const;
export const JOB_STATE_SCHEDULED = "scheduled" as const;

export type JobState =
  | typeof JOB_STATE_AVAILABLE
  | typeof JOB_STATE_CANCELLED
  | typeof JOB_STATE_COMPLETED
  | typeof JOB_STATE_DISCARDED
  | typeof JOB_STATE_PENDING
  | typeof JOB_STATE_RETRYABLE
  | typeof JOB_STATE_RUNNING
  | typeof JOB_STATE_SCHEDULED;

/** Default number of maximum attempts for a job. */
export const MAX_ATTEMPTS_DEFAULT = 25;

/** Default priority for a job. */
export const PRIORITY_DEFAULT = 1;

/** Default queue for a job. */
export const QUEUE_DEFAULT = "default";

/**
 * Interface for job args. Implementations must provide a `kind` string that
 * uniquely identifies the job type in the database.
 *
 * Implementations should define a `toJSON()` method to control which fields
 * are serialized as the job's args. If `toJSON()` is not defined, all
 * properties except `kind` and `insertOpts` are serialized.
 *
 * They may optionally provide `insertOpts` to set default insertion options
 * for all jobs of this kind.
 *
 * Example:
 *
 *     class SortArgs implements JobArgs {
 *       kind = "sort";
 *
 *       constructor(public strings: string[]) {}
 *
 *       toJSON() {
 *         return { strings: this.strings };
 *       }
 *     }
 */
export interface JobArgs {
  kind: string;
  insertOpts?: InsertOpts;
}

/**
 * Provides a way to create job args from a plain object for quick insertion
 * without defining a class.
 *
 * Example:
 *
 *     const args = new JobArgsObject("sort", { strings: ["whale", "tiger"] });
 *     await client.insert(args);
 */
export class JobArgsObject implements JobArgs {
  readonly kind: string;
  private readonly obj: Record<string, unknown>;

  constructor(kind: string, obj: Record<string, unknown>) {
    if (!kind) throw new Error("kind is required");
    if (!obj) throw new Error("obj is required");
    this.kind = kind;
    this.obj = obj;
  }

  toJSON(): Record<string, unknown> {
    return this.obj;
  }
}

/** A failed job work attempt containing information about the error. */
export interface AttemptError {
  at: Date;
  attempt: number;
  error: string;
  trace: string;
}

/** Contains the properties of a job that are persisted to the database. */
export interface JobRow {
  /** ID of the job, generated by a Postgres sequence. */
  id: number;

  /** The job's args as an object decoded from JSON. */
  args: Record<string, unknown>;

  /** The attempt number of the job. Jobs are inserted at 0. */
  attempt: number;

  /** The time that the job was last worked. */
  attemptedAt: Date | null;

  /** The set of worker IDs that have worked this job. */
  attemptedBy: string[] | null;

  /** When the job record was created. */
  createdAt: Date;

  /** Errors from previous work attempts, ordered earliest to latest. */
  errors: AttemptError[] | null;

  /** When the job was finalized (completed successfully or discarded). */
  finalizedAt: Date | null;

  /** Kind uniquely identifies the type of job and which worker should work it. */
  kind: string;

  /** The maximum number of attempts before the job is discarded. */
  maxAttempts: number;

  /** Arbitrary metadata associated with the job. */
  metadata: Record<string, unknown>;

  /** Priority of the job, 1 (highest) to 4 (lowest). */
  priority: number;

  /** The queue where the job will be worked. */
  queue: string;

  /** When the job is scheduled to become available for work. */
  scheduledAt: Date;

  /** The current state of the job. */
  state: JobState;

  /** Arbitrary tags for grouping and categorizing jobs. */
  tags: string[];

  /** Unique key for the job, generated by objing unique opts configuration. */
  uniqueKey: Uint8Array | null;

  /** States considered for uniqueness checks. */
  uniqueStates: JobState[] | null;
}
