import { Buffer } from "node:buffer";

import { describe, expect, it } from "vitest";

import type { JobListOrderBy, JobListParams } from "./driver.js";
import { ValidationError } from "./errors.js";
import { JOB_STATE, type JobState } from "./job.js";
import {
  decodeJobListCursor,
  encodeJobListCursor,
  encodeQueueCursor,
  jobListKeyset,
  jobListKeysetSql,
  normalizeJobDeleteManyOptions,
  normalizeJobListOptions,
  normalizeQueueListOptions,
  normalizeJobUpdateOptions,
} from "./query.js";

const ALL_STATES = Object.values(JOB_STATE);

describe("query normalization", () => {
  it("normalizes metadata containment and output independently", () => {
    expect(
      normalizeJobListOptions({ metadata: { tenant: "acme" } })
    ).toMatchObject({
      metadata: { tenant: "acme" },
    });
    expect(
      normalizeJobUpdateOptions({
        metadata: { preserved: true },
        output: null,
      })
    ).toEqual({ metadata: { preserved: true }, output: null });
  });

  it("accepts only metadata and output in job updates, like Go and Rust", () => {
    expect(normalizeJobUpdateOptions({})).toEqual({});
    for (const key of [
      "maxAttempts",
      "priority",
      "queue",
      "scheduledAt",
      "state",
      "tags",
    ]) {
      expect(() => normalizeJobUpdateOptions({ [key]: 1 })).toThrow(
        new ValidationError(
          `job update ${key} is not an option; expected one of metadata, output`
        )
      );
    }
  });

  it("requires explicit bounded authorization for bulk deletion", () => {
    expect(() => normalizeJobDeleteManyOptions({})).toThrow(
      "requires a filter or all: true"
    );
    expect(() =>
      normalizeJobDeleteManyOptions({ all: true, ids: [1n] })
    ).toThrow("cannot be combined");
    expect(normalizeJobDeleteManyOptions({ ids: [1n], limit: 10 })).toEqual({
      all: false,
      ids: [1n],
      kinds: [],
      limit: 10,
      priorities: [],
      queues: [],
      states: [],
    });
  });

  // Generated by River for Go's `JobListCursor.MarshalText` for jobs with
  // the same fields, in UTC as Go's drivers return times, listed in
  // `states` (every state when absent).
  const goCursors: readonly {
    readonly cursor: string;
    readonly job: Record<string, unknown>;
    readonly name: string;
    readonly orderBy: JobListOrderBy;
    readonly states?: readonly JobState[];
    readonly time: string | null;
  }[] = [
    {
      cursor:
        "eyJpZCI6MSwia2luZCI6ImNvbmZvcm1hbmNlX2VjaG8iLCJxdWV1ZSI6ImRlZmF1bHQiLCJzb3J0X2ZpZWxkIjoiaWQiLCJ0aW1lIjoiMDAwMS0wMS0wMVQwMDowMDowMFoifQ==",
      job: { id: 1n, kind: "conformance_echo", queue: "default" },
      name: "an ID cursor",
      orderBy: "id",
      time: null,
    },
    {
      cursor:
        "eyJpZCI6OTIyMzM3MjAzNjg1NDc3NTgwNywia2luZCI6ImFcdTAwM2NiXHUwMDNlXHUwMDI2Y1x1MjAyOFx1MjAyOVx1MDAwMVx0XCJcXCIsInF1ZXVlIjoiccOp8J-YgCIsInNvcnRfZmllbGQiOiJpZCIsInRpbWUiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiJ9",
      job: {
        id: 9_223_372_036_854_775_807n,
        kind: 'a<b>&c\u2028\u2029\u0001\t"\\',
        queue: "q\u00e9\u{1f600}",
      },
      name: "Go's string escaping and the largest ID",
      orderBy: "id",
      time: null,
    },
    {
      cursor:
        "eyJpZCI6NDIsImtpbmQiOiJlbWFpbCIsInF1ZXVlIjoiZGVmYXVsdCIsInNvcnRfZmllbGQiOiJzY2hlZHVsZWRfYXQiLCJ0aW1lIjoiMjAyNi0wMS0wMlQwMzowNDowNS4xMjM0NTY3ODlaIn0=",
      job: {
        id: 42n,
        kind: "email",
        queue: "default",
        scheduledAt: "2026-01-02T03:04:05.123456789Z",
      },
      name: "a nanosecond scheduled time",
      orderBy: "scheduledAt",
      time: "2026-01-02T03:04:05.123456789Z",
    },
    {
      cursor:
        "eyJpZCI6OTAwNzE5OTI1NDc0MDk5Mywia2luZCI6ImVtYWlsIiwicXVldWUiOiJjcml0aWNhbCIsInNvcnRfZmllbGQiOiJzY2hlZHVsZWRfYXQiLCJ0aW1lIjoiMjA5OS0xMi0zMVQyMzo1OTo1OS4xMloifQ==",
      job: {
        id: 9_007_199_254_740_993n,
        kind: "email",
        queue: "critical",
        scheduledAt: "2099-12-31T23:59:59.120Z",
      },
      name: "trailing fractional zeros",
      orderBy: "scheduledAt",
      time: "2099-12-31T23:59:59.12Z",
    },
    {
      cursor:
        "eyJpZCI6Nywia2luZCI6InJlcG9ydD94PTEiLCJxdWV1ZSI6ImRlZmF1bHQiLCJzb3J0X2ZpZWxkIjoiZmluYWxpemVkX2F0IiwidGltZSI6IjIwMjYtMDEtMDJUMDM6MDQ6MDYuNVoifQ==",
      job: {
        finalizedAt: "2026-01-02T03:04:06.5Z",
        id: 7n,
        kind: "report?x=1",
        queue: "default",
        state: "completed",
      },
      name: "a finalized time",
      orderBy: "finalizedAt",
      states: ["completed"],
      time: "2026-01-02T03:04:06.5Z",
    },
    {
      cursor:
        "eyJpZCI6OCwia2luZCI6InN5bmN-IiwicXVldWUiOiJkZWZhdWx0Iiwic29ydF9maWVsZCI6InRpbWUiLCJ0aW1lIjoiMjAyNi0wMS0wMlQwMzowNDowNy4wMDAwMDFaIn0=",
      job: {
        attemptedAt: "2026-01-02T03:04:07.000001Z",
        id: 8n,
        kind: "sync~",
        queue: "default",
        state: "running",
      },
      name: "a running job's attempt time",
      orderBy: "time",
      states: ["running"],
      time: "2026-01-02T03:04:07.000001Z",
    },
    {
      cursor:
        "eyJpZCI6OSwia2luZCI6InN5bmMiLCJxdWV1ZSI6ImRlZmF1bHQiLCJzb3J0X2ZpZWxkIjoidGltZSIsInRpbWUiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiJ9",
      job: {
        attemptedAt: null,
        createdAt: "2026-01-01T00:00:00.25Z",
        id: 9n,
        kind: "sync",
        queue: "default",
        state: "running",
      },
      name: "a running job without an attempt time",
      orderBy: "time",
      states: ["running"],
      time: null,
    },
    {
      cursor:
        "eyJpZCI6MTAsImtpbmQiOiJzeW5jIiwicXVldWUiOiJkZWZhdWx0Iiwic29ydF9maWVsZCI6InRpbWUiLCJ0aW1lIjoiMDAwMS0wMS0wMVQwMDowMDowMFoifQ==",
      job: {
        createdAt: "2026-01-01T00:00:01Z",
        finalizedAt: null,
        id: 10n,
        kind: "sync",
        queue: "default",
        state: "completed",
      },
      name: "a completed job without a finalized time among unfinalized states",
      orderBy: "time",
      states: ["completed", "running"],
      time: null,
    },
    {
      cursor:
        "eyJpZCI6MTIsImtpbmQiOiJzeW5jIiwicXVldWUiOiJkZWZhdWx0Iiwic29ydF9maWVsZCI6InRpbWUiLCJ0aW1lIjoiMjAyNi0wMS0wMlQwMzowNDowNS41WiJ9",
      job: {
        attemptedAt: "2026-01-02T03:04:05.5Z",
        finalizedAt: "2026-01-02T03:04:09Z",
        id: 12n,
        kind: "sync",
        queue: "default",
        state: "completed",
      },
      name: "a completed job listed by the first state's field",
      orderBy: "time",
      states: ["running", "completed"],
      time: "2026-01-02T03:04:05.5Z",
    },
    {
      cursor:
        "eyJpZCI6MTMsImtpbmQiOiJzeW5jIiwicXVldWUiOiJkZWZhdWx0Iiwic29ydF9maWVsZCI6InRpbWUiLCJ0aW1lIjoiMDAwMS0wMS0wMVQwMDowMDowMFoifQ==",
      job: {
        finalizedAt: null,
        id: 13n,
        kind: "sync",
        queue: "default",
        scheduledAt: "2026-01-02T03:04:05Z",
        state: "available",
      },
      name: "an unfinalized job listed by finalized time",
      orderBy: "time",
      states: ["completed", "available"],
      time: null,
    },
    {
      cursor:
        "eyJpZCI6MTQsImtpbmQiOiJzeW5jIiwicXVldWUiOiJkZWZhdWx0Iiwic29ydF9maWVsZCI6InRpbWUiLCJ0aW1lIjoiMjAyNi0wMS0wMlQwMzowNDowNVoifQ==",
      job: {
        id: 14n,
        kind: "sync",
        queue: "default",
        scheduledAt: "2026-01-02T03:04:05Z",
        state: "running",
      },
      name: "time ordering without a state filter",
      orderBy: "time",
      states: [],
      time: "2026-01-02T03:04:05Z",
    },
    {
      cursor:
        "eyJpZCI6MTEsImtpbmQiOiJzeW5jIiwicXVldWUiOiJkZWZhdWx0Iiwic29ydF9maWVsZCI6InRpbWUiLCJ0aW1lIjoiMDAwMS0wMS0wMVQwMDowMDowMC4wMDAwMDAwMDFaIn0=",
      job: {
        id: 11n,
        kind: "sync",
        queue: "default",
        scheduledAt: "0001-01-01T00:00:00.000000001Z",
        state: "available",
      },
      name: "a time just after Go's zero time",
      orderBy: "time",
      time: "0001-01-01T00:00:00.000000001Z",
    },
  ];

  it.each(goCursors.map((golden) => [golden.name, golden] as const))(
    "encodes job list cursors byte for byte like Go: %s",
    (_name, { cursor, job, orderBy, states }) => {
      const row = Object.fromEntries(
        Object.entries(job).map(([key, value]) => [
          key,
          key.endsWith("At") && typeof value === "string"
            ? Temporal.Instant.from(value)
            : value,
        ])
      );
      expect(
        encodeJobListCursor(row as never, {
          sortField: orderBy,
          states: states ?? ALL_STATES,
        })
      ).toBe(cursor);
    }
  );

  it.each(goCursors.map((golden) => [golden.name, golden] as const))(
    "decodes Go cursors without losing signed 64-bit IDs: %s",
    (_name, { cursor, job, orderBy, states, time }) => {
      const expected = {
        id: job.id,
        kind: job.kind,
        queue: job.queue,
        sortField: orderBy,
        time: time === null ? null : Temporal.Instant.from(time),
      };
      expect(decodeJobListCursor(cursor)).toEqual(expected);
      const { after } = normalizeJobListOptions({
        after: cursor,
        orderBy,
        ...(states === undefined ? {} : { states }),
      });
      expect(after).toEqual(expected);
    }
  );

  it("decodes cursors in either base64 alphabet, with or without padding", () => {
    // Go's cursor for this job contains `-`, so its alphabets differ.
    const cursor = goCursors.find(
      ({ name }) => name === "a running job's attempt time"
    )!.cursor;
    expect(cursor).toMatch(/-/);
    const expected = decodeJobListCursor(cursor);
    const standard = cursor.replaceAll("-", "+").replaceAll("_", "/");
    for (const spelling of [
      standard,
      cursor.replace(/=+$/, ""),
      standard.replace(/=+$/, ""),
    ]) {
      expect(decodeJobListCursor(spelling)).toEqual(expected);
    }
  });

  it("decodes Go's zero time as no time and ignores unknown fields", () => {
    const encode = (payload: string) =>
      Buffer.from(payload, "utf8").toString("base64");
    expect(
      decodeJobListCursor(
        encode(
          '{"id":5,"kind":"k","queue":"q","sort_field":"scheduled_at",' +
            '"time":"0001-01-01T00:00:00Z","extra":true}'
        )
      )
    ).toEqual({
      id: 5n,
      kind: "k",
      queue: "q",
      sortField: "scheduledAt",
      time: null,
    });
    // ID ordering ignores the time, and offsets are normalized.
    expect(
      decodeJobListCursor(
        encode(
          '{"id":-1,"kind":"","queue":"","sort_field":"id",' +
            '"time":"2026-01-02T04:04:05+01:00"}'
        )
      )
    ).toEqual({ id: -1n, kind: "", queue: "", sortField: "id", time: null });
    expect(
      decodeJobListCursor(
        encode(
          '{"id":5,"kind":"k","queue":"q","sort_field":"time",' +
            '"time":"2026-01-02T04:04:05+01:00"}'
        )
      ).time
    ).toEqual(Temporal.Instant.from("2026-01-02T03:04:05Z"));
  });

  it("rejects job times Go can't encode in a cursor", () => {
    expect(() =>
      encodeJobListCursor(
        {
          id: 1n,
          kind: "k",
          queue: "q",
          scheduledAt: Temporal.Instant.from("+010000-01-01T00:00:00Z"),
        } as never,
        { sortField: "scheduledAt", states: ALL_STATES }
      )
    ).toThrow(ValidationError);
  });

  const goPayload = (fields: string) =>
    Buffer.from(`{${fields}}`, "utf8").toString("base64url");
  it.each([
    ["text that isn't base64", "not base64!"],
    ["mixed base64 alphabets", "eyJp-+"],
    ["misplaced padding", "eyJ=pZCI6"],
    [
      "River for JavaScript's earlier cursor envelope",
      Buffer.from(
        '{"id":"1","kind":"x","queue":"q","sortField":"id","time":null,"v":1}'
      ).toString("base64url"),
    ],
    [
      "a string ID",
      goPayload(
        '"id":"1","kind":"x","queue":"q","sort_field":"id","time":"0001-01-01T00:00:00Z"'
      ),
    ],
    [
      "a fractional ID",
      goPayload(
        '"id":1.5,"kind":"x","queue":"q","sort_field":"id","time":"0001-01-01T00:00:00Z"'
      ),
    ],
    [
      "an ID beyond int64",
      goPayload(
        '"id":9223372036854775808,"kind":"x","queue":"q","sort_field":"id","time":"0001-01-01T00:00:00Z"'
      ),
    ],
    [
      "an unknown sort field",
      goPayload(
        '"id":1,"kind":"x","queue":"q","sort_field":"created_at","time":"0001-01-01T00:00:00Z"'
      ),
    ],
    [
      "a missing time",
      goPayload('"id":1,"kind":"x","queue":"q","sort_field":"id"'),
    ],
    [
      "a year Go can't parse",
      goPayload(
        '"id":1,"kind":"x","queue":"q","sort_field":"time","time":"+010000-01-01T00:00:00Z"'
      ),
    ],
    [
      "invalid UTF-8",
      Buffer.concat([
        Buffer.from('{"id":1,"kind":"'),
        Buffer.from([0xf0, 0x90, 0x30, 0x80]),
        Buffer.from(
          '","queue":"q","sort_field":"id","time":"0001-01-01T00:00:00Z"}'
        ),
      ]).toString("base64url"),
    ],
    ["a queue cursor", encodeQueueCursor({ name: "default" } as never)],
  ])("rejects a job list cursor with %s", (_name, after) => {
    expect(() => normalizeJobListOptions({ after })).toThrow(
      /invalid .*cursor/
    );
  });

  it("round-trips strict queue cursors", () => {
    const cursor = encodeQueueCursor({ name: "default" } as never);
    expect(normalizeQueueListOptions({ after: cursor })).toMatchObject({
      nameAfter: "default",
    });
  });

  it("renders each job list keyset as SQL like Go", () => {
    const time = Temporal.Instant.from("2026-01-02T03:04:05Z");
    const render = (
      params: Pick<
        JobListParams,
        "after" | "sortDirection" | "sortField" | "states"
      >
    ) => {
      const bound: unknown[] = [];
      const sql = jobListKeysetSql(jobListKeyset(params), (value) => {
        bound.push(value);
        return `$${bound.length}`;
      });
      return { ...sql, bound };
    };
    const cursor = (value: Temporal.Instant | null) => ({
      id: 7n,
      kind: "k",
      queue: "q",
      sortField: "time" as const,
      time: value,
    });

    expect(
      render({
        after: null,
        sortDirection: "asc",
        sortField: "id",
        states: [],
      })
    ).toEqual({ after: null, bound: [], orderBy: "id ASC" });
    // Nulls sort last ascending and first descending when the field may be
    // null for a listed state.
    expect(
      render({
        after: cursor(time),
        sortDirection: "asc",
        sortField: "time",
        states: ["completed", "available"],
      })
    ).toEqual({
      after:
        "(finalized_at > $1 OR (finalized_at = $2 AND id > $3) OR finalized_at IS NULL)",
      bound: [time, time, 7n],
      orderBy: "finalized_at ASC NULLS LAST, id ASC",
    });
    expect(
      render({
        after: cursor(time),
        sortDirection: "desc",
        sortField: "time",
        states: ["running"],
      })
    ).toEqual({
      after: "(attempted_at < $1 OR (attempted_at = $2 AND id < $3))",
      bound: [time, time, 7n],
      orderBy: "attempted_at DESC NULLS FIRST, id DESC",
    });
    // A cursor without a time resumes within the nulls, or by ID alone
    // when the field can't be null.
    expect(
      render({
        after: cursor(null),
        sortDirection: "asc",
        sortField: "time",
        states: ["running"],
      })
    ).toMatchObject({ after: "(attempted_at IS NULL AND id > $1)" });
    expect(
      render({
        after: cursor(null),
        sortDirection: "desc",
        sortField: "time",
        states: ["running"],
      })
    ).toMatchObject({ after: "(attempted_at IS NOT NULL OR id < $1)" });
    expect(
      render({
        after: cursor(null),
        sortDirection: "asc",
        sortField: "time",
        states: [],
      })
    ).toEqual({
      after: "id > $1",
      bound: [7n],
      orderBy: "scheduled_at ASC, id ASC",
    });
    expect(
      render({
        after: { ...cursor(time), sortField: "finalizedAt" },
        sortDirection: "asc",
        sortField: "finalizedAt",
        states: ["completed"],
      })
    ).toMatchObject({
      after: "(finalized_at > $1 OR (finalized_at = $2 AND id > $3))",
      orderBy: "finalized_at ASC, id ASC",
    });
  });
});
