version: 2
updates:
  - cooldown:
      default-days: 7
    directory: "/"
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
