// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package dbsqlc

import (
	"database/sql"
	"time"
)

type RiverJob struct {
	ID           int64
	Args         []byte
	Attempt      int64
	AttemptedAt  sql.NullTime
	AttemptedBy  []byte
	CreatedAt    time.Time
	Errors       []byte
	FinalizedAt  sql.NullTime
	Kind         string
	MaxAttempts  int64
	Metadata     []byte
	Priority     int16
	Queue        string
	State        string
	ScheduledAt  time.Time
	Tags         []byte
	UniqueKey    sql.NullString
	UniqueStates sql.NullInt16
}

type RiverLeader struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	LeaderID  string
	Name      string
}

type RiverMigration struct {
	Line      string
	Version   int64
	CreatedAt time.Time
}

type RiverNotification struct {
	ID        int64
	CreatedAt time.Time
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  sql.NullTime
	UpdatedAt time.Time
}

type Statistics struct {
	IndexName   string
	TableName   string
	TableSchema string
}

type Tables struct {
	TableName   string
	TableSchema string
}
