// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_job.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const jobCancelExec = `-- name: JobCancelExec :execresult
UPDATE /* TEMPLATE: schema */river_job
SET
    state = CASE WHEN state = 'running' THEN state ELSE 'cancelled' END,
    finalized_at = CASE WHEN state = 'running' THEN finalized_at ELSE COALESCE(?, NOW(6)) END,
    metadata = JSON_SET(metadata, '$.cancel_attempted_at', CAST(? AS CHAR))
WHERE id = ?
    AND state NOT IN ('cancelled', 'completed', 'discarded')
    AND finalized_at IS NULL
`

type JobCancelExecParams struct {
	Now               sql.NullTime
	CancelAttemptedAt interface{}
	ID                int64
}

func (q *Queries) JobCancelExec(ctx context.Context, db DBTX, arg *JobCancelExecParams) (sql.Result, error) {
	return db.ExecContext(ctx, jobCancelExec, arg.Now, arg.CancelAttemptedAt, arg.ID)
}

const jobCountByAllStates = `-- name: JobCountByAllStates :many
SELECT state, count(*) AS count
FROM /* TEMPLATE: schema */river_job
GROUP BY state
`

type JobCountByAllStatesRow struct {
	State string
	Count int64
}

func (q *Queries) JobCountByAllStates(ctx context.Context, db DBTX) ([]*JobCountByAllStatesRow, error) {
	rows, err := db.QueryContext(ctx, jobCountByAllStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*JobCountByAllStatesRow
	for rows.Next() {
		var i JobCountByAllStatesRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobCountByQueueAndState = `-- name: JobCountByQueueAndState :many
WITH all_queues AS (
    SELECT DISTINCT river_job.queue
    FROM /* TEMPLATE: schema */river_job
    WHERE river_job.queue IN (/*SLICE:queue_names*/?)
),

running_job_counts AS (
    SELECT river_job.queue, COUNT(*) AS count
    FROM /* TEMPLATE: schema */river_job
    WHERE river_job.queue IN (/*SLICE:queue_names*/?)
        AND river_job.state = 'running'
    GROUP BY river_job.queue
),

available_job_counts AS (
    SELECT river_job.queue, COUNT(*) AS count
    FROM /* TEMPLATE: schema */river_job
    WHERE river_job.queue IN (/*SLICE:queue_names*/?)
        AND river_job.state = 'available'
    GROUP BY river_job.queue
)

SELECT
    all_queues.queue,
    COALESCE(available_job_counts.count, 0) AS count_available,
    COALESCE(running_job_counts.count, 0) AS count_running
FROM all_queues
LEFT JOIN running_job_counts ON all_queues.queue = running_job_counts.queue
LEFT JOIN available_job_counts ON all_queues.queue = available_job_counts.queue
ORDER BY all_queues.queue ASC
`

type JobCountByQueueAndStateParams struct {
	QueueNames []string
}

type JobCountByQueueAndStateRow struct {
	Queue          string
	CountAvailable int64
	CountRunning   int64
}

func (q *Queries) JobCountByQueueAndState(ctx context.Context, db DBTX, arg *JobCountByQueueAndStateParams) ([]*JobCountByQueueAndStateRow, error) {
	query := jobCountByQueueAndState
	var queryParams []interface{}
	if len(arg.QueueNames) > 0 {
		for _, v := range arg.QueueNames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:queue_names*/?", strings.Repeat(",?", len(arg.QueueNames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:queue_names*/?", "NULL", 1)
	}
	if len(arg.QueueNames) > 0 {
		for _, v := range arg.QueueNames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:queue_names*/?", strings.Repeat(",?", len(arg.QueueNames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:queue_names*/?", "NULL", 1)
	}
	if len(arg.QueueNames) > 0 {
		for _, v := range arg.QueueNames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:queue_names*/?", strings.Repeat(",?", len(arg.QueueNames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:queue_names*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*JobCountByQueueAndStateRow
	for rows.Next() {
		var i JobCountByQueueAndStateRow
		if err := rows.Scan(&i.Queue, &i.CountAvailable, &i.CountRunning); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobCountByState = `-- name: JobCountByState :one
SELECT count(*) AS count
FROM /* TEMPLATE: schema */river_job
WHERE state = ?
`

func (q *Queries) JobCountByState(ctx context.Context, db DBTX, state string) (int64, error) {
	row := db.QueryRowContext(ctx, jobCountByState, state)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const jobDeleteBefore = `-- name: JobDeleteBefore :execresult
DELETE FROM /* TEMPLATE: schema */river_job
WHERE
    id IN (
        SELECT id FROM (
            SELECT rj2.id
            FROM /* TEMPLATE: schema */river_job rj2
            WHERE
                (rj2.state = 'cancelled' AND rj2.finalized_at < ?) OR
                (rj2.state = 'completed' AND rj2.finalized_at < ?) OR
                (rj2.state = 'discarded' AND rj2.finalized_at < ?)
            ORDER BY rj2.id
            LIMIT ?
        ) AS tmp
    )
    AND (
        CAST(? AS SIGNED)
        OR river_job.queue NOT IN (/*SLICE:queues_excluded*/?)
    )
`

type JobDeleteBeforeParams struct {
	CancelledFinalizedAtHorizon sql.NullTime
	CompletedFinalizedAtHorizon sql.NullTime
	DiscardedFinalizedAtHorizon sql.NullTime
	Limit                       int32
	QueuesExcludedEmpty         int64
	QueuesExcluded              []string
}

func (q *Queries) JobDeleteBefore(ctx context.Context, db DBTX, arg *JobDeleteBeforeParams) (sql.Result, error) {
	query := jobDeleteBefore
	var queryParams []interface{}
	queryParams = append(queryParams, arg.CancelledFinalizedAtHorizon)
	queryParams = append(queryParams, arg.CompletedFinalizedAtHorizon)
	queryParams = append(queryParams, arg.DiscardedFinalizedAtHorizon)
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.QueuesExcludedEmpty)
	if len(arg.QueuesExcluded) > 0 {
		for _, v := range arg.QueuesExcluded {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:queues_excluded*/?", strings.Repeat(",?", len(arg.QueuesExcluded))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:queues_excluded*/?", "NULL", 1)
	}
	return db.ExecContext(ctx, query, queryParams...)
}

const jobDeleteExec = `-- name: JobDeleteExec :execresult
DELETE FROM /* TEMPLATE: schema */river_job
WHERE id = ?
    AND river_job.state != 'running'
`

func (q *Queries) JobDeleteExec(ctx context.Context, db DBTX, id int64) (sql.Result, error) {
	return db.ExecContext(ctx, jobDeleteExec, id)
}

const jobDeleteManyExec = `-- name: JobDeleteManyExec :exec
DELETE FROM /* TEMPLATE: schema */river_job
WHERE id IN (/*SLICE:id*/?)
`

func (q *Queries) JobDeleteManyExec(ctx context.Context, db DBTX, id []int64) error {
	query := jobDeleteManyExec
	var queryParams []interface{}
	if len(id) > 0 {
		for _, v := range id {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:id*/?", strings.Repeat(",?", len(id))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:id*/?", "NULL", 1)
	}
	_, err := db.ExecContext(ctx, query, queryParams...)
	return err
}

const jobDeleteManySelect = `-- name: JobDeleteManySelect :many
SELECT id, args, attempt, attempted_at, attempted_by, created_at, errors, finalized_at, kind, max_attempts, metadata, priority, queue, state, scheduled_at, tags, unique_key, unique_states
FROM /* TEMPLATE: schema */river_job
WHERE id IN (
    SELECT id FROM (
        SELECT id
        FROM /* TEMPLATE: schema */river_job
        WHERE /* TEMPLATE_BEGIN: where_clause */ true /* TEMPLATE_END */
            AND state != 'running'
        ORDER BY /* TEMPLATE_BEGIN: order_by_clause */ id /* TEMPLATE_END */
        LIMIT ?
    ) AS tmp
)
ORDER BY id
`

func (q *Queries) JobDeleteManySelect(ctx context.Context, db DBTX, limit int32) ([]*RiverJob, error) {
	rows, err := db.QueryContext(ctx, jobDeleteManySelect, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverJob
	for rows.Next() {
		var i RiverJob
		if err := rows.Scan(
			&i.ID,
			&i.Args,
			&i.Attempt,
			&i.AttemptedAt,
			&i.AttemptedBy,
			&i.CreatedAt,
			&i.Errors,
			&i.FinalizedAt,
			&i.Kind,
			&i.MaxAttempts,
			&i.Metadata,
			&i.Priority,
			&i.Queue,
			&i.State,
			&i.ScheduledAt,
			&i.Tags,
			&i.UniqueKey,
			&i.UniqueStates,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobGetAvailableIDs = `-- name: JobGetAvailableIDs :many
SELECT id
FROM /* TEMPLATE: schema */river_job
WHERE
    priority >= 0
    AND queue = ?
    AND scheduled_at <= COALESCE(?, NOW(6))
    AND state = 'available'
ORDER BY priority ASC, scheduled_at ASC, id ASC
LIMIT ?
FOR UPDATE SKIP LOCKED
`

type JobGetAvailableIDsParams struct {
	Queue string
	Now   sql.NullTime
	Limit int32
}

func (q *Queries) JobGetAvailableIDs(ctx context.Context, db DBTX, arg *JobGetAvailableIDsParams) ([]int64, error) {
	rows, err := db.QueryContext(ctx, jobGetAvailableIDs, arg.Queue, arg.Now, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobGetAvailableUpdate = `-- name: JobGetAvailableUpdate :exec
UPDATE /* TEMPLATE: schema */river_job
SET
    attempt = attempt + 1,
    attempted_at = COALESCE(?, NOW(6)),
    attempted_by = JSON_ARRAY_APPEND(
        CASE
            WHEN JSON_LENGTH(COALESCE(attempted_by, JSON_ARRAY())) < CAST(? AS SIGNED)
                THEN COALESCE(attempted_by, JSON_ARRAY())
            WHEN CAST(? AS SIGNED) <= 1
                THEN JSON_ARRAY()
            ELSE COALESCE(
                JSON_EXTRACT(
                    attempted_by,
                    CONCAT('$[last-', CAST(? AS SIGNED) - 2, ' to last]')
                ),
                JSON_ARRAY()
            )
        END,
        '$',
        CAST(? AS CHAR)
    ),
    state = 'running'
WHERE id IN (/*SLICE:id*/?)
`

type JobGetAvailableUpdateParams struct {
	Now            sql.NullTime
	MaxAttemptedBy int64
	AttemptedBy    interface{}
	ID             []int64
}

func (q *Queries) JobGetAvailableUpdate(ctx context.Context, db DBTX, arg *JobGetAvailableUpdateParams) error {
	query := jobGetAvailableUpdate
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Now)
	queryParams = append(queryParams, arg.MaxAttemptedBy)
	queryParams = append(queryParams, arg.MaxAttemptedBy)
	queryParams = append(queryParams, arg.MaxAttemptedBy)
	queryParams = append(queryParams, arg.AttemptedBy)
	if len(arg.ID) > 0 {
		for _, v := range arg.ID {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:id*/?", strings.Repeat(",?", len(arg.ID))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:id*/?", "NULL", 1)
	}
	_, err := db.ExecContext(ctx, query, queryParams...)
	return err
}

const jobGetByID = `-- name: JobGetByID :one
SELECT id, args, attempt, attempted_at, attempted_by, created_at, errors, finalized_at, kind, max_attempts, metadata, priority, queue, state, scheduled_at, tags, unique_key, unique_states
FROM /* TEMPLATE: schema */river_job
WHERE id = ?
LIMIT 1
`

func (q *Queries) JobGetByID(ctx context.Context, db DBTX, id int64) (*RiverJob, error) {
	row := db.QueryRowContext(ctx, jobGetByID, id)
	var i RiverJob
	err := row.Scan(
		&i.ID,
		&i.Args,
		&i.Attempt,
		&i.AttemptedAt,
		&i.AttemptedBy,
		&i.CreatedAt,
		&i.Errors,
		&i.FinalizedAt,
		&i.Kind,
		&i.MaxAttempts,
		&i.Metadata,
		&i.Priority,
		&i.Queue,
		&i.State,
		&i.ScheduledAt,
		&i.Tags,
		&i.UniqueKey,
		&i.UniqueStates,
	)
	return &i, err
}

const jobGetByIDMany = `-- name: JobGetByIDMany :many
SELECT id, args, attempt, attempted_at, attempted_by, created_at, errors, finalized_at, kind, max_attempts, metadata, priority, queue, state, scheduled_at, tags, unique_key, unique_states
FROM /* TEMPLATE: schema */river_job
WHERE id IN (/*SLICE:id*/?)
ORDER BY id
`

func (q *Queries) JobGetByIDMany(ctx context.Context, db DBTX, id []int64) ([]*RiverJob, error) {
	query := jobGetByIDMany
	var queryParams []interface{}
	if len(id) > 0 {
		for _, v := range id {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:id*/?", strings.Repeat(",?", len(id))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:id*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverJob
	for rows.Next() {
		var i RiverJob
		if err := rows.Scan(
			&i.ID,
			&i.Args,
			&i.Attempt,
			&i.AttemptedAt,
			&i.AttemptedBy,
			&i.CreatedAt,
			&i.Errors,
			&i.FinalizedAt,
			&i.Kind,
			&i.MaxAttempts,
			&i.Metadata,
			&i.Priority,
			&i.Queue,
			&i.State,
			&i.ScheduledAt,
			&i.Tags,
			&i.UniqueKey,
			&i.UniqueStates,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobGetByIDManyOrdered = `-- name: JobGetByIDManyOrdered :many
SELECT id, args, attempt, attempted_at, attempted_by, created_at, errors, finalized_at, kind, max_attempts, metadata, priority, queue, state, scheduled_at, tags, unique_key, unique_states
FROM /* TEMPLATE: schema */river_job
WHERE id IN (/*SLICE:id*/?)
ORDER BY priority ASC, scheduled_at ASC, id ASC
`

func (q *Queries) JobGetByIDManyOrdered(ctx context.Context, db DBTX, id []int64) ([]*RiverJob, error) {
	query := jobGetByIDManyOrdered
	var queryParams []interface{}
	if len(id) > 0 {
		for _, v := range id {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:id*/?", strings.Repeat(",?", len(id))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:id*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverJob
	for rows.Next() {
		var i RiverJob
		if err := rows.Scan(
			&i.ID,
			&i.Args,
			&i.Attempt,
			&i.AttemptedAt,
			&i.AttemptedBy,
			&i.CreatedAt,
			&i.Errors,
			&i.FinalizedAt,
			&i.Kind,
			&i.MaxAttempts,
			&i.Metadata,
			&i.Priority,
			&i.Queue,
			&i.State,
			&i.ScheduledAt,
			&i.Tags,
			&i.UniqueKey,
			&i.UniqueStates,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobGetByKindMany = `-- name: JobGetByKindMany :many
SELECT id, args, attempt, attempted_at, attempted_by, created_at, errors, finalized_at, kind, max_attempts, metadata, priority, queue, state, scheduled_at, tags, unique_key, unique_states
FROM /* TEMPLATE: schema */river_job
WHERE kind IN (/*SLICE:kind*/?)
ORDER BY id
`

func (q *Queries) JobGetByKindMany(ctx context.Context, db DBTX, kind []string) ([]*RiverJob, error) {
	query := jobGetByKindMany
	var queryParams []interface{}
	if len(kind) > 0 {
		for _, v := range kind {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kind*/?", strings.Repeat(",?", len(kind))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kind*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverJob
	for rows.Next() {
		var i RiverJob
		if err := rows.Scan(
			&i.ID,
			&i.Args,
			&i.Attempt,
			&i.AttemptedAt,
			&i.AttemptedBy,
			&i.CreatedAt,
			&i.Errors,
			&i.FinalizedAt,
			&i.Kind,
			&i.MaxAttempts,
			&i.Metadata,
			&i.Priority,
			&i.Queue,
			&i.State,
			&i.ScheduledAt,
			&i.Tags,
			&i.UniqueKey,
			&i.UniqueStates,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobGetStuck = `-- name: JobGetStuck :many
SELECT id, args, attempt, attempted_at, attempted_by, created_at, errors, finalized_at, kind, max_attempts, metadata, priority, queue, state, scheduled_at, tags, unique_key, unique_states
FROM /* TEMPLATE: schema */river_job
WHERE state = 'running'
    AND attempted_at < ?
ORDER BY id
LIMIT ?
`

type JobGetStuckParams struct {
	StuckHorizon sql.NullTime
	Limit        int32
}

func (q *Queries) JobGetStuck(ctx context.Context, db DBTX, arg *JobGetStuckParams) ([]*RiverJob, error) {
	rows, err := db.QueryContext(ctx, jobGetStuck, arg.StuckHorizon, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverJob
	for rows.Next() {
		var i RiverJob
		if err := rows.Scan(
			&i.ID,
			&i.Args,
			&i.Attempt,
			&i.AttemptedAt,
			&i.AttemptedBy,
			&i.CreatedAt,
			&i.Errors,
			&i.FinalizedAt,
			&i.Kind,
			&i.MaxAttempts,
			&i.Metadata,
			&i.Priority,
			&i.Queue,
			&i.State,
			&i.ScheduledAt,
			&i.Tags,
			&i.UniqueKey,
			&i.UniqueStates,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobInsertFast = `-- name: JobInsertFast :execresult
INSERT INTO /* TEMPLATE: schema */river_job(
    id,
    args,
    created_at,
    kind,
    max_attempts,
    metadata,
    priority,
    queue,
    scheduled_at,
    state,
    tags,
    unique_key,
    unique_states
) VALUES (
    ?,
    ?,
    COALESCE(?, NOW(6)),
    ?,
    ?,
    CAST(? AS JSON),
    ?,
    ?,
    COALESCE(?, NOW(6)),
    ?,
    CAST(? AS JSON),
    ?,
    ?
)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id), kind = VALUES(kind)
`

type JobInsertFastParams struct {
	ID           sql.NullInt64
	Args         []byte
	CreatedAt    interface{}
	Kind         string
	MaxAttempts  int64
	Metadata     []byte
	Priority     int16
	Queue        string
	ScheduledAt  interface{}
	State        string
	Tags         []byte
	UniqueKey    sql.NullString
	UniqueStates sql.NullInt16
}

func (q *Queries) JobInsertFast(ctx context.Context, db DBTX, arg *JobInsertFastParams) (sql.Result, error) {
	return db.ExecContext(ctx, jobInsertFast,
		arg.ID,
		arg.Args,
		arg.CreatedAt,
		arg.Kind,
		arg.MaxAttempts,
		arg.Metadata,
		arg.Priority,
		arg.Queue,
		arg.ScheduledAt,
		arg.State,
		arg.Tags,
		arg.UniqueKey,
		arg.UniqueStates,
	)
}

const jobInsertFullExec = `-- name: JobInsertFullExec :execlastid
INSERT INTO /* TEMPLATE: schema */river_job(
    args,
    attempt,
    attempted_at,
    attempted_by,
    created_at,
    errors,
    finalized_at,
    kind,
    max_attempts,
    metadata,
    priority,
    queue,
    scheduled_at,
    state,
    tags,
    unique_key,
    unique_states
) VALUES (
    ?,
    ?,
    ?,
    CAST(? AS JSON),
    COALESCE(?, NOW(6)),
    CAST(? AS JSON),
    ?,
    ?,
    ?,
    CAST(? AS JSON),
    ?,
    ?,
    COALESCE(?, NOW(6)),
    ?,
    CAST(? AS JSON),
    ?,
    ?
)
`

type JobInsertFullExecParams struct {
	Args         []byte
	Attempt      int64
	AttemptedAt  sql.NullTime
	AttemptedBy  []byte
	CreatedAt    interface{}
	Errors       []byte
	FinalizedAt  sql.NullTime
	Kind         string
	MaxAttempts  int64
	Metadata     []byte
	Priority     int16
	Queue        string
	ScheduledAt  interface{}
	State        string
	Tags         []byte
	UniqueKey    sql.NullString
	UniqueStates sql.NullInt16
}

func (q *Queries) JobInsertFullExec(ctx context.Context, db DBTX, arg *JobInsertFullExecParams) (int64, error) {
	result, err := db.ExecContext(ctx, jobInsertFullExec,
		arg.Args,
		arg.Attempt,
		arg.AttemptedAt,
		arg.AttemptedBy,
		arg.CreatedAt,
		arg.Errors,
		arg.FinalizedAt,
		arg.Kind,
		arg.MaxAttempts,
		arg.Metadata,
		arg.Priority,
		arg.Queue,
		arg.ScheduledAt,
		arg.State,
		arg.Tags,
		arg.UniqueKey,
		arg.UniqueStates,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const jobKindList = `-- name: JobKindList :many
SELECT DISTINCT kind
FROM /* TEMPLATE: schema */river_job
WHERE (? = '' OR LOWER(kind) COLLATE utf8mb4_general_ci LIKE CONCAT('%', LOWER(?), '%'))
    AND (? = '' OR kind COLLATE utf8mb4_general_ci > ?)
    AND kind NOT IN (/*SLICE:exclude*/?)
ORDER BY kind ASC
LIMIT ?
`

type JobKindListParams struct {
	Match   string
	After   interface{}
	Exclude []string
	Limit   int32
}

func (q *Queries) JobKindList(ctx context.Context, db DBTX, arg *JobKindListParams) ([]string, error) {
	query := jobKindList
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Match)
	queryParams = append(queryParams, arg.Match)
	queryParams = append(queryParams, arg.After)
	queryParams = append(queryParams, arg.After)
	if len(arg.Exclude) > 0 {
		for _, v := range arg.Exclude {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:exclude*/?", strings.Repeat(",?", len(arg.Exclude))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:exclude*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var kind string
		if err := rows.Scan(&kind); err != nil {
			return nil, err
		}
		items = append(items, kind)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobList = `-- name: JobList :many
SELECT id, args, attempt, attempted_at, attempted_by, created_at, errors, finalized_at, kind, max_attempts, metadata, priority, queue, state, scheduled_at, tags, unique_key, unique_states
FROM /* TEMPLATE: schema */river_job
WHERE /* TEMPLATE_BEGIN: where_clause */ true /* TEMPLATE_END */
ORDER BY /* TEMPLATE_BEGIN: order_by_clause */ id /* TEMPLATE_END */
LIMIT ?
`

func (q *Queries) JobList(ctx context.Context, db DBTX, limit int32) ([]*RiverJob, error) {
	rows, err := db.QueryContext(ctx, jobList, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverJob
	for rows.Next() {
		var i RiverJob
		if err := rows.Scan(
			&i.ID,
			&i.Args,
			&i.Attempt,
			&i.AttemptedAt,
			&i.AttemptedBy,
			&i.CreatedAt,
			&i.Errors,
			&i.FinalizedAt,
			&i.Kind,
			&i.MaxAttempts,
			&i.Metadata,
			&i.Priority,
			&i.Queue,
			&i.State,
			&i.ScheduledAt,
			&i.Tags,
			&i.UniqueKey,
			&i.UniqueStates,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobRescue = `-- name: JobRescue :exec
UPDATE /* TEMPLATE: schema */river_job
SET
    errors = JSON_ARRAY_APPEND(COALESCE(errors, JSON_ARRAY()), '$', CAST(? AS JSON)),
    finalized_at = ?,
    scheduled_at = ?,
    metadata = JSON_SET(
        metadata,
        '$."river:rescue_count"',
        COALESCE(
            CASE JSON_TYPE(JSON_EXTRACT(metadata, '$."river:rescue_count"'))
                WHEN 'INTEGER' THEN JSON_EXTRACT(metadata, '$."river:rescue_count"')
                WHEN 'DOUBLE' THEN JSON_EXTRACT(metadata, '$."river:rescue_count"')
                ELSE NULL
            END,
            0
        ) + 1
    ),
    state = ?
WHERE id = ?
`

type JobRescueParams struct {
	Error       []byte
	FinalizedAt sql.NullTime
	ScheduledAt time.Time
	State       string
	ID          int64
}

func (q *Queries) JobRescue(ctx context.Context, db DBTX, arg *JobRescueParams) error {
	_, err := db.ExecContext(ctx, jobRescue,
		arg.Error,
		arg.FinalizedAt,
		arg.ScheduledAt,
		arg.State,
		arg.ID,
	)
	return err
}

const jobRetryExec = `-- name: JobRetryExec :execresult
UPDATE /* TEMPLATE: schema */river_job
SET
    state = 'available',
    max_attempts = CASE WHEN attempt = max_attempts THEN max_attempts + 1 ELSE max_attempts END,
    finalized_at = NULL,
    scheduled_at = COALESCE(?, NOW(6))
WHERE id = ?
    AND state != 'running'
    AND (
        state <> 'available'
        OR scheduled_at > COALESCE(?, NOW(6))
    )
`

type JobRetryExecParams struct {
	Now sql.NullTime
	ID  int64
}

func (q *Queries) JobRetryExec(ctx context.Context, db DBTX, arg *JobRetryExecParams) (sql.Result, error) {
	return db.ExecContext(ctx, jobRetryExec, arg.Now, arg.ID, arg.Now)
}

const jobSchedule = `-- name: JobSchedule :many
WITH eligible AS (
    SELECT river_job.id, river_job.unique_key, river_job.unique_states, river_job.priority, river_job.scheduled_at,
        CASE
            WHEN river_job.unique_key IS NOT NULL AND river_job.unique_states IS NOT NULL THEN
                ROW_NUMBER() OVER (PARTITION BY river_job.unique_key ORDER BY river_job.priority, river_job.scheduled_at, river_job.id)
            ELSE NULL
        END AS row_num
    FROM /* TEMPLATE: schema */river_job
    WHERE
        river_job.state IN ('retryable', 'scheduled')
        AND river_job.scheduled_at <= COALESCE(?, NOW(6))
    ORDER BY
        river_job.priority,
        river_job.scheduled_at,
        river_job.id
    LIMIT ?
),
unique_conflicts AS (
    SELECT DISTINCT eligible.unique_key
    FROM /* TEMPLATE: schema */river_job
    JOIN eligible
        ON river_job.unique_key = eligible.unique_key
        AND river_job.id != eligible.id
    WHERE
        river_job.unique_key IS NOT NULL
        AND river_job.unique_states IS NOT NULL
        AND CASE river_job.state
                WHEN 'available' THEN river_job.unique_states & (1 << 0)
                WHEN 'cancelled' THEN river_job.unique_states & (1 << 1)
                WHEN 'completed' THEN river_job.unique_states & (1 << 2)
                WHEN 'discarded' THEN river_job.unique_states & (1 << 3)
                WHEN 'pending'   THEN river_job.unique_states & (1 << 4)
                WHEN 'retryable' THEN river_job.unique_states & (1 << 5)
                WHEN 'running'   THEN river_job.unique_states & (1 << 6)
                WHEN 'scheduled' THEN river_job.unique_states & (1 << 7)
                ELSE 0
            END >= 1
)
SELECT eligible.id,
    CASE
        WHEN eligible.unique_key IS NULL OR eligible.unique_states IS NULL THEN FALSE
        WHEN uc.unique_key IS NOT NULL THEN TRUE
        WHEN eligible.row_num > 1 THEN TRUE
        ELSE FALSE
    END AS conflict_discarded
FROM eligible
LEFT JOIN unique_conflicts uc ON eligible.unique_key = uc.unique_key
ORDER BY eligible.priority, eligible.scheduled_at, eligible.id
`

type JobScheduleParams struct {
	Now   sql.NullTime
	Limit int32
}

type JobScheduleRow struct {
	ID                int64
	ConflictDiscarded int64
}

func (q *Queries) JobSchedule(ctx context.Context, db DBTX, arg *JobScheduleParams) ([]*JobScheduleRow, error) {
	rows, err := db.QueryContext(ctx, jobSchedule, arg.Now, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*JobScheduleRow
	for rows.Next() {
		var i JobScheduleRow
		if err := rows.Scan(&i.ID, &i.ConflictDiscarded); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobScheduleSetAvailableExec = `-- name: JobScheduleSetAvailableExec :exec
UPDATE /* TEMPLATE: schema */river_job
SET state = 'available'
WHERE id IN (/*SLICE:id*/?)
`

func (q *Queries) JobScheduleSetAvailableExec(ctx context.Context, db DBTX, id []int64) error {
	query := jobScheduleSetAvailableExec
	var queryParams []interface{}
	if len(id) > 0 {
		for _, v := range id {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:id*/?", strings.Repeat(",?", len(id))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:id*/?", "NULL", 1)
	}
	_, err := db.ExecContext(ctx, query, queryParams...)
	return err
}

const jobScheduleSetDiscardedExec = `-- name: JobScheduleSetDiscardedExec :exec
UPDATE /* TEMPLATE: schema */river_job
SET metadata = JSON_MERGE_PATCH(metadata, '{"unique_key_conflict": "scheduler_discarded"}'),
    finalized_at = COALESCE(?, NOW(6)),
    state = 'discarded'
WHERE id IN (/*SLICE:id*/?)
`

type JobScheduleSetDiscardedExecParams struct {
	Now sql.NullTime
	ID  []int64
}

func (q *Queries) JobScheduleSetDiscardedExec(ctx context.Context, db DBTX, arg *JobScheduleSetDiscardedExecParams) error {
	query := jobScheduleSetDiscardedExec
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Now)
	if len(arg.ID) > 0 {
		for _, v := range arg.ID {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:id*/?", strings.Repeat(",?", len(arg.ID))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:id*/?", "NULL", 1)
	}
	_, err := db.ExecContext(ctx, query, queryParams...)
	return err
}

const jobSetMetadataIfNotRunningExec = `-- name: JobSetMetadataIfNotRunningExec :execresult
UPDATE /* TEMPLATE: schema */river_job
SET metadata = JSON_MERGE_PATCH(metadata, CAST(? AS JSON))
WHERE id = ?
    AND state != 'running'
`

type JobSetMetadataIfNotRunningExecParams struct {
	MetadataUpdates []byte
	ID              int64
}

func (q *Queries) JobSetMetadataIfNotRunningExec(ctx context.Context, db DBTX, arg *JobSetMetadataIfNotRunningExecParams) (sql.Result, error) {
	return db.ExecContext(ctx, jobSetMetadataIfNotRunningExec, arg.MetadataUpdates, arg.ID)
}

const jobSetStateIfRunningExec = `-- name: JobSetStateIfRunningExec :exec
UPDATE /* TEMPLATE: schema */river_job
SET
    attempt      = CASE WHEN (CAST(? AS CHAR) <> 'retryable' AND ? <> 'scheduled' OR JSON_EXTRACT(metadata, '$.cancel_attempted_at') IS NULL) AND CAST(? AS SIGNED)
                    THEN ?
                    ELSE attempt END,
    errors       = CASE WHEN CAST(? AS SIGNED)
                    THEN JSON_ARRAY_APPEND(COALESCE(errors, JSON_ARRAY()), '$', CAST(? AS JSON))
                    ELSE errors END,
    finalized_at = CASE WHEN ((? = 'retryable' OR ? = 'scheduled') AND JSON_EXTRACT(metadata, '$.cancel_attempted_at') IS NOT NULL)
                    THEN COALESCE(?, NOW(6))
                    WHEN CAST(? AS SIGNED)
                    THEN ?
                    ELSE finalized_at END,
    metadata     = CASE WHEN CAST(? AS SIGNED)
                    THEN JSON_MERGE_PATCH(metadata, CAST(? AS JSON))
                    ELSE metadata END,
    scheduled_at = CASE WHEN (CAST(? AS CHAR) <> 'retryable' AND ? <> 'scheduled' OR JSON_EXTRACT(metadata, '$.cancel_attempted_at') IS NULL) AND CAST(? AS SIGNED)
                    THEN ?
                    ELSE scheduled_at END,
    state        = CASE WHEN ((? = 'retryable' OR ? = 'scheduled') AND JSON_EXTRACT(metadata, '$.cancel_attempted_at') IS NOT NULL)
                    THEN 'cancelled'
                    ELSE ? END
WHERE id = ?
    AND state = 'running'
`

type JobSetStateIfRunningExecParams struct {
	State               string
	AttemptDoUpdate     int64
	Attempt             int64
	ErrorsDoUpdate      int64
	Error               []byte
	Now                 sql.NullTime
	FinalizedAtDoUpdate int64
	FinalizedAt         sql.NullTime
	MetadataDoMerge     int64
	MetadataUpdates     []byte
	ScheduledAtDoUpdate int64
	ScheduledAt         time.Time
	ID                  int64
}

func (q *Queries) JobSetStateIfRunningExec(ctx context.Context, db DBTX, arg *JobSetStateIfRunningExecParams) error {
	_, err := db.ExecContext(ctx, jobSetStateIfRunningExec,
		arg.State,
		arg.State,
		arg.AttemptDoUpdate,
		arg.Attempt,
		arg.ErrorsDoUpdate,
		arg.Error,
		arg.State,
		arg.State,
		arg.Now,
		arg.FinalizedAtDoUpdate,
		arg.FinalizedAt,
		arg.MetadataDoMerge,
		arg.MetadataUpdates,
		arg.State,
		arg.State,
		arg.ScheduledAtDoUpdate,
		arg.ScheduledAt,
		arg.State,
		arg.State,
		arg.State,
		arg.ID,
	)
	return err
}

const jobUpdateExec = `-- name: JobUpdateExec :exec
UPDATE /* TEMPLATE: schema */river_job
SET
    metadata = CASE WHEN CAST(? AS SIGNED) THEN JSON_MERGE_PATCH(metadata, CAST(? AS JSON)) ELSE metadata END
WHERE id = ?
`

type JobUpdateExecParams struct {
	MetadataDoMerge int64
	Metadata        []byte
	ID              int64
}

func (q *Queries) JobUpdateExec(ctx context.Context, db DBTX, arg *JobUpdateExecParams) error {
	_, err := db.ExecContext(ctx, jobUpdateExec, arg.MetadataDoMerge, arg.Metadata, arg.ID)
	return err
}

const jobUpdateFullExec = `-- name: JobUpdateFullExec :exec
UPDATE /* TEMPLATE: schema */river_job
SET
    attempt = CASE WHEN CAST(? AS SIGNED) THEN ? ELSE attempt END,
    attempted_at = CASE WHEN CAST(? AS SIGNED) THEN ? ELSE attempted_at END,
    attempted_by = CASE WHEN CAST(? AS SIGNED) THEN CAST(? AS JSON) ELSE attempted_by END,
    errors = CASE WHEN CAST(? AS SIGNED) THEN CAST(? AS JSON) ELSE errors END,
    finalized_at = CASE WHEN CAST(? AS SIGNED) THEN ? ELSE finalized_at END,
    max_attempts = CASE WHEN CAST(? AS SIGNED) THEN ? ELSE max_attempts END,
    metadata = CASE WHEN CAST(? AS SIGNED) THEN CAST(? AS JSON) ELSE metadata END,
    state = CASE WHEN CAST(? AS SIGNED) THEN ? ELSE state END
WHERE id = ?
`

type JobUpdateFullExecParams struct {
	AttemptDoUpdate     int64
	Attempt             int64
	AttemptedAtDoUpdate int64
	AttemptedAt         sql.NullTime
	AttemptedByDoUpdate int64
	AttemptedBy         []byte
	ErrorsDoUpdate      int64
	Errors              []byte
	FinalizedAtDoUpdate int64
	FinalizedAt         sql.NullTime
	MaxAttemptsDoUpdate int64
	MaxAttempts         int64
	MetadataDoUpdate    int64
	Metadata            []byte
	StateDoUpdate       int64
	State               string
	ID                  int64
}

func (q *Queries) JobUpdateFullExec(ctx context.Context, db DBTX, arg *JobUpdateFullExecParams) error {
	_, err := db.ExecContext(ctx, jobUpdateFullExec,
		arg.AttemptDoUpdate,
		arg.Attempt,
		arg.AttemptedAtDoUpdate,
		arg.AttemptedAt,
		arg.AttemptedByDoUpdate,
		arg.AttemptedBy,
		arg.ErrorsDoUpdate,
		arg.Errors,
		arg.FinalizedAtDoUpdate,
		arg.FinalizedAt,
		arg.MaxAttemptsDoUpdate,
		arg.MaxAttempts,
		arg.MetadataDoUpdate,
		arg.Metadata,
		arg.StateDoUpdate,
		arg.State,
		arg.ID,
	)
	return err
}
