// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_migration.sql

package dbsqlc

import (
	"context"
	"strings"
	"time"
)

const riverMigrationDeleteAssumingMainMany = `-- name: RiverMigrationDeleteAssumingMainMany :many
SELECT created_at, version
FROM /* TEMPLATE: schema */river_migration
WHERE version IN (/*SLICE:version*/?)
`

type RiverMigrationDeleteAssumingMainManyRow struct {
	CreatedAt time.Time
	Version   int64
}

func (q *Queries) RiverMigrationDeleteAssumingMainMany(ctx context.Context, db DBTX, version []int64) ([]*RiverMigrationDeleteAssumingMainManyRow, error) {
	query := riverMigrationDeleteAssumingMainMany
	var queryParams []interface{}
	if len(version) > 0 {
		for _, v := range version {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:version*/?", strings.Repeat(",?", len(version))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:version*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigrationDeleteAssumingMainManyRow
	for rows.Next() {
		var i RiverMigrationDeleteAssumingMainManyRow
		if err := rows.Scan(&i.CreatedAt, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationDeleteAssumingMainManyExec = `-- name: RiverMigrationDeleteAssumingMainManyExec :exec
DELETE FROM /* TEMPLATE: schema */river_migration
WHERE version IN (/*SLICE:version*/?)
`

func (q *Queries) RiverMigrationDeleteAssumingMainManyExec(ctx context.Context, db DBTX, version []int64) error {
	query := riverMigrationDeleteAssumingMainManyExec
	var queryParams []interface{}
	if len(version) > 0 {
		for _, v := range version {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:version*/?", strings.Repeat(",?", len(version))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:version*/?", "NULL", 1)
	}
	_, err := db.ExecContext(ctx, query, queryParams...)
	return err
}

const riverMigrationDeleteByLineAndVersionMany = `-- name: RiverMigrationDeleteByLineAndVersionMany :many
SELECT line, version, created_at
FROM /* TEMPLATE: schema */river_migration
WHERE line = ?
    AND version IN (/*SLICE:version*/?)
`

type RiverMigrationDeleteByLineAndVersionManyParams struct {
	Line    string
	Version []int64
}

func (q *Queries) RiverMigrationDeleteByLineAndVersionMany(ctx context.Context, db DBTX, arg *RiverMigrationDeleteByLineAndVersionManyParams) ([]*RiverMigration, error) {
	query := riverMigrationDeleteByLineAndVersionMany
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Line)
	if len(arg.Version) > 0 {
		for _, v := range arg.Version {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:version*/?", strings.Repeat(",?", len(arg.Version))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:version*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigration
	for rows.Next() {
		var i RiverMigration
		if err := rows.Scan(&i.Line, &i.Version, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationDeleteByLineAndVersionManyExec = `-- name: RiverMigrationDeleteByLineAndVersionManyExec :exec
DELETE FROM /* TEMPLATE: schema */river_migration
WHERE line = ?
    AND version IN (/*SLICE:version*/?)
`

type RiverMigrationDeleteByLineAndVersionManyExecParams struct {
	Line    string
	Version []int64
}

func (q *Queries) RiverMigrationDeleteByLineAndVersionManyExec(ctx context.Context, db DBTX, arg *RiverMigrationDeleteByLineAndVersionManyExecParams) error {
	query := riverMigrationDeleteByLineAndVersionManyExec
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Line)
	if len(arg.Version) > 0 {
		for _, v := range arg.Version {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:version*/?", strings.Repeat(",?", len(arg.Version))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:version*/?", "NULL", 1)
	}
	_, err := db.ExecContext(ctx, query, queryParams...)
	return err
}

const riverMigrationGetAllAssumingMain = `-- name: RiverMigrationGetAllAssumingMain :many
SELECT
    created_at,
    version
FROM /* TEMPLATE: schema */river_migration
ORDER BY version
`

type RiverMigrationGetAllAssumingMainRow struct {
	CreatedAt time.Time
	Version   int64
}

func (q *Queries) RiverMigrationGetAllAssumingMain(ctx context.Context, db DBTX) ([]*RiverMigrationGetAllAssumingMainRow, error) {
	rows, err := db.QueryContext(ctx, riverMigrationGetAllAssumingMain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigrationGetAllAssumingMainRow
	for rows.Next() {
		var i RiverMigrationGetAllAssumingMainRow
		if err := rows.Scan(&i.CreatedAt, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationGetByLine = `-- name: RiverMigrationGetByLine :many
SELECT line, version, created_at
FROM /* TEMPLATE: schema */river_migration
WHERE line = ?
ORDER BY version
`

func (q *Queries) RiverMigrationGetByLine(ctx context.Context, db DBTX, line string) ([]*RiverMigration, error) {
	rows, err := db.QueryContext(ctx, riverMigrationGetByLine, line)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigration
	for rows.Next() {
		var i RiverMigration
		if err := rows.Scan(&i.Line, &i.Version, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationGetByLineAndVersion = `-- name: RiverMigrationGetByLineAndVersion :one
SELECT line, version, created_at
FROM /* TEMPLATE: schema */river_migration
WHERE line = ? AND version = ?
`

type RiverMigrationGetByLineAndVersionParams struct {
	Line    string
	Version int64
}

func (q *Queries) RiverMigrationGetByLineAndVersion(ctx context.Context, db DBTX, arg *RiverMigrationGetByLineAndVersionParams) (*RiverMigration, error) {
	row := db.QueryRowContext(ctx, riverMigrationGetByLineAndVersion, arg.Line, arg.Version)
	var i RiverMigration
	err := row.Scan(&i.Line, &i.Version, &i.CreatedAt)
	return &i, err
}

const riverMigrationGetByLineAndVersionMany = `-- name: RiverMigrationGetByLineAndVersionMany :many
SELECT line, version, created_at
FROM /* TEMPLATE: schema */river_migration
WHERE line = ? AND version IN (/*SLICE:version*/?)
ORDER BY version
`

type RiverMigrationGetByLineAndVersionManyParams struct {
	Line    string
	Version []int64
}

func (q *Queries) RiverMigrationGetByLineAndVersionMany(ctx context.Context, db DBTX, arg *RiverMigrationGetByLineAndVersionManyParams) ([]*RiverMigration, error) {
	query := riverMigrationGetByLineAndVersionMany
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Line)
	if len(arg.Version) > 0 {
		for _, v := range arg.Version {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:version*/?", strings.Repeat(",?", len(arg.Version))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:version*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigration
	for rows.Next() {
		var i RiverMigration
		if err := rows.Scan(&i.Line, &i.Version, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationGetByVersion = `-- name: RiverMigrationGetByVersion :one
SELECT created_at, version
FROM /* TEMPLATE: schema */river_migration
WHERE version = ?
`

type RiverMigrationGetByVersionRow struct {
	CreatedAt time.Time
	Version   int64
}

func (q *Queries) RiverMigrationGetByVersion(ctx context.Context, db DBTX, version int64) (*RiverMigrationGetByVersionRow, error) {
	row := db.QueryRowContext(ctx, riverMigrationGetByVersion, version)
	var i RiverMigrationGetByVersionRow
	err := row.Scan(&i.CreatedAt, &i.Version)
	return &i, err
}

const riverMigrationGetByVersionMany = `-- name: RiverMigrationGetByVersionMany :many
SELECT created_at, version
FROM /* TEMPLATE: schema */river_migration
WHERE version IN (/*SLICE:version*/?)
ORDER BY version
`

type RiverMigrationGetByVersionManyRow struct {
	CreatedAt time.Time
	Version   int64
}

func (q *Queries) RiverMigrationGetByVersionMany(ctx context.Context, db DBTX, version []int64) ([]*RiverMigrationGetByVersionManyRow, error) {
	query := riverMigrationGetByVersionMany
	var queryParams []interface{}
	if len(version) > 0 {
		for _, v := range version {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:version*/?", strings.Repeat(",?", len(version))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:version*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigrationGetByVersionManyRow
	for rows.Next() {
		var i RiverMigrationGetByVersionManyRow
		if err := rows.Scan(&i.CreatedAt, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationInsertAssumingMainExec = `-- name: RiverMigrationInsertAssumingMainExec :exec
INSERT INTO /* TEMPLATE: schema */river_migration (
    version
) VALUES (
    ?
)
`

func (q *Queries) RiverMigrationInsertAssumingMainExec(ctx context.Context, db DBTX, version int64) error {
	_, err := db.ExecContext(ctx, riverMigrationInsertAssumingMainExec, version)
	return err
}

const riverMigrationInsertExec = `-- name: RiverMigrationInsertExec :exec
INSERT INTO /* TEMPLATE: schema */river_migration (
    line,
    version
) VALUES (
    ?,
    ?
)
`

type RiverMigrationInsertExecParams struct {
	Line    string
	Version int64
}

func (q *Queries) RiverMigrationInsertExec(ctx context.Context, db DBTX, arg *RiverMigrationInsertExecParams) error {
	_, err := db.ExecContext(ctx, riverMigrationInsertExec, arg.Line, arg.Version)
	return err
}
