// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_notification.sql

package dbsqlc

import (
	"context"
	"time"
)

const notificationDeleteBefore = `-- name: NotificationDeleteBefore :execrows
DELETE FROM /* TEMPLATE: schema */river_notification
WHERE created_at < ?
ORDER BY created_at, id
LIMIT ?
`

type NotificationDeleteBeforeParams struct {
	CreatedAtHorizon time.Time
	Limit            int32
}

func (q *Queries) NotificationDeleteBefore(ctx context.Context, db DBTX, arg *NotificationDeleteBeforeParams) (int64, error) {
	result, err := db.ExecContext(ctx, notificationDeleteBefore, arg.CreatedAtHorizon, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const notificationGetAfter = `-- name: NotificationGetAfter :many
SELECT id, created_at, payload, topic
FROM /* TEMPLATE: schema */river_notification
WHERE id > ?
ORDER BY id ASC
LIMIT ?
FOR SHARE
`

type NotificationGetAfterParams struct {
	After int64
	Limit int32
}

// InnoDB allocates auto-increment IDs before commit, so IDs may commit out of
// order. The ascending locking read waits for an earlier uncommitted row rather
// than returning a later committed row and causing the listener to skip it.
func (q *Queries) NotificationGetAfter(ctx context.Context, db DBTX, arg *NotificationGetAfterParams) ([]*RiverNotification, error) {
	rows, err := db.QueryContext(ctx, notificationGetAfter, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverNotification
	for rows.Next() {
		var i RiverNotification
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Payload,
			&i.Topic,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationGetIDsForUpdate = `-- name: NotificationGetIDsForUpdate :many
SELECT id
FROM /* TEMPLATE: schema */river_notification
ORDER BY id
FOR UPDATE
`

// Used to establish a listener's initial high-water mark. This intentionally
// scans in ascending order instead of using MAX(id) or a descending LIMIT so
// that it encounters and waits for any lower uncommitted auto-increment IDs.
func (q *Queries) NotificationGetIDsForUpdate(ctx context.Context, db DBTX) ([]int64, error) {
	rows, err := db.QueryContext(ctx, notificationGetIDsForUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationInsert = `-- name: NotificationInsert :exec
INSERT INTO /* TEMPLATE: schema */river_notification (
    payload,
    topic
) VALUES (
    ?,
    ?
)
`

type NotificationInsertParams struct {
	Payload string
	Topic   string
}

func (q *Queries) NotificationInsert(ctx context.Context, db DBTX, arg *NotificationInsertParams) error {
	_, err := db.ExecContext(ctx, notificationInsert, arg.Payload, arg.Topic)
	return err
}

const notificationInsertJobCancel = `-- name: NotificationInsertJobCancel :exec
INSERT INTO /* TEMPLATE: schema */river_notification (payload, topic)
VALUES (
    JSON_OBJECT('action', 'cancel', 'job_id', CAST(? AS SIGNED), 'queue', CAST(? AS CHAR)),
    ?
)
`

type NotificationInsertJobCancelParams struct {
	JobID int64
	Queue interface{}
	Topic string
}

func (q *Queries) NotificationInsertJobCancel(ctx context.Context, db DBTX, arg *NotificationInsertJobCancelParams) error {
	_, err := db.ExecContext(ctx, notificationInsertJobCancel, arg.JobID, arg.Queue, arg.Topic)
	return err
}
