// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_notification.sql

package dbsqlc

import (
	"context"
	"time"
)

const notificationDeleteBefore = `-- name: NotificationDeleteBefore :execrows
DELETE FROM /* TEMPLATE: schema */river_notification
WHERE created_at < ?
`

func (q *Queries) NotificationDeleteBefore(ctx context.Context, db DBTX, createdAtHorizon time.Time) (int64, error) {
	result, err := db.ExecContext(ctx, notificationDeleteBefore, createdAtHorizon)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const notificationGetAfterForUpdate = `-- name: NotificationGetAfterForUpdate :one
SELECT id, created_at, payload, topic
FROM /* TEMPLATE: schema */river_notification
WHERE id > ?
ORDER BY id ASC
LIMIT 1
FOR UPDATE
`

func (q *Queries) NotificationGetAfterForUpdate(ctx context.Context, db DBTX, after int64) (*RiverNotification, error) {
	row := db.QueryRowContext(ctx, notificationGetAfterForUpdate, after)
	var i RiverNotification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Payload,
		&i.Topic,
	)
	return &i, err
}

const notificationGetLastID = `-- name: NotificationGetLastID :one
SELECT CAST(COALESCE(MAX(id), 0) AS SIGNED)
FROM /* TEMPLATE: schema */river_notification
`

func (q *Queries) NotificationGetLastID(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRowContext(ctx, notificationGetLastID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const notificationInsert = `-- name: NotificationInsert :exec
INSERT INTO /* TEMPLATE: schema */river_notification (
    payload,
    topic
) VALUES (
    ?,
    ?
)
`

type NotificationInsertParams struct {
	Payload string
	Topic   string
}

func (q *Queries) NotificationInsert(ctx context.Context, db DBTX, arg *NotificationInsertParams) error {
	_, err := db.ExecContext(ctx, notificationInsert, arg.Payload, arg.Topic)
	return err
}
