// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_leader.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const leaderAttemptElectExec = `-- name: LeaderAttemptElectExec :execresult
INSERT IGNORE INTO /* TEMPLATE: schema */river_leader (
    leader_id,
    elected_at,
    expires_at
) VALUES (
    ?,
    COALESCE(?, NOW(6)),
    TIMESTAMPADD(MICROSECOND, ?, COALESCE(?, NOW(6)))
)
`

type LeaderAttemptElectExecParams struct {
	LeaderID string
	Now      interface{}
	TTL      int64
}

func (q *Queries) LeaderAttemptElectExec(ctx context.Context, db DBTX, arg *LeaderAttemptElectExecParams) (sql.Result, error) {
	return db.ExecContext(ctx, leaderAttemptElectExec,
		arg.LeaderID,
		arg.Now,
		arg.TTL,
		arg.Now,
	)
}

const leaderAttemptReelectExec = `-- name: LeaderAttemptReelectExec :execresult
UPDATE /* TEMPLATE: schema */river_leader
SET expires_at = TIMESTAMPADD(MICROSECOND, ?, COALESCE(?, NOW(6)))
WHERE
    elected_at = ?
    AND expires_at >= COALESCE(?, NOW(6))
    AND leader_id = ?
`

type LeaderAttemptReelectExecParams struct {
	TTL       int64
	Now       sql.NullTime
	ElectedAt time.Time
	LeaderID  string
}

func (q *Queries) LeaderAttemptReelectExec(ctx context.Context, db DBTX, arg *LeaderAttemptReelectExecParams) (sql.Result, error) {
	return db.ExecContext(ctx, leaderAttemptReelectExec,
		arg.TTL,
		arg.Now,
		arg.ElectedAt,
		arg.Now,
		arg.LeaderID,
	)
}

const leaderDeleteExpired = `-- name: LeaderDeleteExpired :execrows
DELETE FROM /* TEMPLATE: schema */river_leader
WHERE expires_at < COALESCE(?, NOW(6))
`

func (q *Queries) LeaderDeleteExpired(ctx context.Context, db DBTX, now sql.NullTime) (int64, error) {
	result, err := db.ExecContext(ctx, leaderDeleteExpired, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const leaderGetElectedLeader = `-- name: LeaderGetElectedLeader :one
SELECT elected_at, expires_at, leader_id, name
FROM /* TEMPLATE: schema */river_leader
`

func (q *Queries) LeaderGetElectedLeader(ctx context.Context, db DBTX) (*RiverLeader, error) {
	row := db.QueryRowContext(ctx, leaderGetElectedLeader)
	var i RiverLeader
	err := row.Scan(
		&i.ElectedAt,
		&i.ExpiresAt,
		&i.LeaderID,
		&i.Name,
	)
	return &i, err
}

const leaderInsertExec = `-- name: LeaderInsertExec :exec
INSERT INTO /* TEMPLATE: schema */river_leader (
    elected_at,
    expires_at,
    leader_id
) VALUES (
    COALESCE(?, ?, NOW(6)),
    COALESCE(?, TIMESTAMPADD(MICROSECOND, ?, COALESCE(?, NOW(6)))),
    ?
)
`

type LeaderInsertExecParams struct {
	ElectedAt interface{}
	Now       interface{}
	ExpiresAt interface{}
	TTL       int64
	LeaderID  string
}

func (q *Queries) LeaderInsertExec(ctx context.Context, db DBTX, arg *LeaderInsertExecParams) error {
	_, err := db.ExecContext(ctx, leaderInsertExec,
		arg.ElectedAt,
		arg.Now,
		arg.ExpiresAt,
		arg.TTL,
		arg.Now,
		arg.LeaderID,
	)
	return err
}

const leaderResign = `-- name: LeaderResign :execrows
DELETE FROM /* TEMPLATE: schema */river_leader
WHERE
    elected_at = ?
    AND leader_id = ?
`

type LeaderResignParams struct {
	ElectedAt time.Time
	LeaderID  string
}

func (q *Queries) LeaderResign(ctx context.Context, db DBTX, arg *LeaderResignParams) (int64, error) {
	result, err := db.ExecContext(ctx, leaderResign, arg.ElectedAt, arg.LeaderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
