// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: schema.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"strings"
)

const indexExists = `-- name: IndexExists :one
SELECT EXISTS (
    SELECT 1
    FROM /* TEMPLATE: information_schema */STATISTICS
    WHERE INDEX_NAME = ?
        AND TABLE_SCHEMA = COALESCE(?, DATABASE())
)
`

type IndexExistsParams struct {
	IndexName string
	Schema    sql.NullString
}

func (q *Queries) IndexExists(ctx context.Context, db DBTX, arg *IndexExistsParams) (bool, error) {
	row := db.QueryRowContext(ctx, indexExists, arg.IndexName, arg.Schema)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const indexGetTableName = `-- name: IndexGetTableName :one
SELECT TABLE_NAME
FROM /* TEMPLATE: information_schema */STATISTICS
WHERE INDEX_NAME = ?
    AND TABLE_SCHEMA = COALESCE(?, DATABASE())
LIMIT 1
`

type IndexGetTableNameParams struct {
	IndexName string
	Schema    sql.NullString
}

func (q *Queries) IndexGetTableName(ctx context.Context, db DBTX, arg *IndexGetTableNameParams) (string, error) {
	row := db.QueryRowContext(ctx, indexGetTableName, arg.IndexName, arg.Schema)
	var table_name string
	err := row.Scan(&table_name)
	return table_name, err
}

const indexesExist = `-- name: IndexesExist :many
SELECT DISTINCT INDEX_NAME AS index_name
FROM /* TEMPLATE: information_schema */STATISTICS
WHERE INDEX_NAME IN (/*SLICE:index_names*/?)
    AND TABLE_SCHEMA = COALESCE(?, DATABASE())
`

type IndexesExistParams struct {
	IndexNames []string
	Schema     sql.NullString
}

func (q *Queries) IndexesExist(ctx context.Context, db DBTX, arg *IndexesExistParams) ([]string, error) {
	query := indexesExist
	var queryParams []interface{}
	if len(arg.IndexNames) > 0 {
		for _, v := range arg.IndexNames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:index_names*/?", strings.Repeat(",?", len(arg.IndexNames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:index_names*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Schema)
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var index_name string
		if err := rows.Scan(&index_name); err != nil {
			return nil, err
		}
		items = append(items, index_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tableExists = `-- name: TableExists :one
SELECT EXISTS (
    SELECT 1
    FROM /* TEMPLATE: information_schema */TABLES
    WHERE TABLE_NAME = ?
        AND TABLE_SCHEMA = COALESCE(?, DATABASE())
)
`

type TableExistsParams struct {
	TableName string
	Schema    sql.NullString
}

func (q *Queries) TableExists(ctx context.Context, db DBTX, arg *TableExistsParams) (bool, error) {
	row := db.QueryRowContext(ctx, tableExists, arg.TableName, arg.Schema)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
