// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_notification.sql

package dbsqlc

import (
	"context"
	"time"
)

const notificationDeleteBefore = `-- name: NotificationDeleteBefore :execrows
DELETE FROM /* TEMPLATE: schema */river_notification
WHERE created_at < $1::timestamptz
`

func (q *Queries) NotificationDeleteBefore(ctx context.Context, db DBTX, createdAtHorizon time.Time) (int64, error) {
	result, err := db.ExecContext(ctx, notificationDeleteBefore, createdAtHorizon)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
