// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: river_job_copyfrom.sql

package dbsqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobInsertFastManyCopyFromParams struct {
	Args         []byte
	CreatedAt    time.Time
	Kind         string
	MaxAttempts  int16
	Metadata     []byte
	Priority     int16
	Queue        string
	ScheduledAt  time.Time
	State        RiverJobState
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}
