// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: river_job_copyfrom.sql

package dbsqlc

import (
	"time"
)

type JobInsertManyParams struct {
	Args        *string
	FinalizedAt *time.Time
	Kind        string
	MaxAttempts int16
	Metadata    string
	Priority    int16
	Queue       string
	ScheduledAt time.Time
	State       RiverJobState
	Tags        []string
}
