// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_notification.sql

package dbsqlc

import (
	"context"
	"time"
)

const notificationDeleteBefore = `-- name: NotificationDeleteBefore :execrows
DELETE FROM /* TEMPLATE: schema */river_notification
WHERE id IN (
    SELECT id
    FROM /* TEMPLATE: schema */river_notification
    WHERE created_at < $1::timestamptz
    ORDER BY created_at, id
    LIMIT $2::bigint
)
`

type NotificationDeleteBeforeParams struct {
	CreatedAtHorizon time.Time
	Max              int64
}

func (q *Queries) NotificationDeleteBefore(ctx context.Context, db DBTX, arg *NotificationDeleteBeforeParams) (int64, error) {
	result, err := db.Exec(ctx, notificationDeleteBefore, arg.CreatedAtHorizon, arg.Max)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
