// Command generatefixtures writes the language-neutral fixtures in
// conformance/testdata by calling River's Go implementation, so Go stays the
// source of truth for values the Rust and JavaScript ports check in their own
// tests. The fixtures are never committed; the directory is ignored by Git
// and the port test targets regenerate it before running.
//
// Run it from anywhere in the repository with `make generate/fixtures`.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// fixtureDir is the directory of generated fixtures relative to the
// repository root.
const fixtureDir = "conformance/testdata"

// referenceNow is the fixed clock most fixtures are generated at.
var referenceNow = time.Date(2026, time.January, 2, 3, 4, 5, 678_900_000, time.UTC) //nolint:gochecknoglobals

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}

	protocolValues, err := makeProtocolValues(root)
	if err != nil {
		return err
	}
	uniqueKeys, err := makeUniqueKeys()
	if err != nil {
		return err
	}
	cronSchedules, err := makeCronSchedules()
	if err != nil {
		return err
	}

	for _, fixture := range []struct {
		name  string
		value any
	}{
		{"cron_schedules.json", cronSchedules},
		{"protocol_values.json", protocolValues},
		{"snooze_counters.json", makeSnoozeCounters()},
		{"unique_keys.json", uniqueKeys},
	} {
		contents, err := json.MarshalIndent(fixture.value, "", "  ")
		if err != nil {
			return fmt.Errorf("error encoding %s: %w", fixture.name, err)
		}
		contents = append(contents, '\n')

		path := filepath.Join(root, fixtureDir, fixture.name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("error creating fixture directory: %w", err)
		}
		if err := os.WriteFile(path, contents, 0o644); err != nil { //nolint:gosec // generated fixtures are world-readable
			return fmt.Errorf("error writing %s: %w", path, err)
		}
	}

	return nil
}

// generatedComment is the `$comment` at the top of every fixture.
func generatedComment(source string) string {
	return "Generated by `make generate/fixtures` from " + source + ". Do not edit."
}

// repoRoot returns the nearest directory at or above the working directory
// that contains go.work, so the command runs the same from any subdirectory.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("error getting working directory: %w", err)
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("go.work not found in the working directory or any parent; run from the River repository")
		}
		dir = parent
	}
}
