// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_migration.sql

package dbsqlc

import (
	"context"
	"strings"
	"time"
)

const riverMigrationDeleteAssumingMainMany = `-- name: RiverMigrationDeleteAssumingMainMany :many
DELETE FROM /* TEMPLATE: schema */river_migration
WHERE version IN (/*SLICE:version*/?)
RETURNING
    created_at,
    version
`

type RiverMigrationDeleteAssumingMainManyRow struct {
	CreatedAt time.Time
	Version   int64
}

func (q *Queries) RiverMigrationDeleteAssumingMainMany(ctx context.Context, db DBTX, version []int64) ([]*RiverMigrationDeleteAssumingMainManyRow, error) {
	query := riverMigrationDeleteAssumingMainMany
	var queryParams []interface{}
	if len(version) > 0 {
		for _, v := range version {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:version*/?", strings.Repeat(",?", len(version))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:version*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigrationDeleteAssumingMainManyRow
	for rows.Next() {
		var i RiverMigrationDeleteAssumingMainManyRow
		if err := rows.Scan(&i.CreatedAt, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationDeleteByLineAndVersionMany = `-- name: RiverMigrationDeleteByLineAndVersionMany :many
DELETE FROM /* TEMPLATE: schema */river_migration
WHERE line = ?1
    AND version IN (/*SLICE:version*/?)
RETURNING line, version, created_at
`

type RiverMigrationDeleteByLineAndVersionManyParams struct {
	Line    string
	Version []int64
}

func (q *Queries) RiverMigrationDeleteByLineAndVersionMany(ctx context.Context, db DBTX, arg *RiverMigrationDeleteByLineAndVersionManyParams) ([]*RiverMigration, error) {
	query := riverMigrationDeleteByLineAndVersionMany
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Line)
	if len(arg.Version) > 0 {
		for _, v := range arg.Version {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:version*/?", strings.Repeat(",?", len(arg.Version))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:version*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigration
	for rows.Next() {
		var i RiverMigration
		if err := rows.Scan(&i.Line, &i.Version, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationGetAllAssumingMain = `-- name: RiverMigrationGetAllAssumingMain :many
SELECT
    created_at,
    version
FROM /* TEMPLATE: schema */river_migration
ORDER BY version
`

type RiverMigrationGetAllAssumingMainRow struct {
	CreatedAt time.Time
	Version   int64
}

// This is a compatibility query for getting existing migrations before the
// `line` column was added to the table in version 005. We need to make sure to
// only select non-line properties so the query doesn't error on older schemas.
// (Even if we use `SELECT *` below, sqlc materializes it to a list of column
// names in the generated query.)
func (q *Queries) RiverMigrationGetAllAssumingMain(ctx context.Context, db DBTX) ([]*RiverMigrationGetAllAssumingMainRow, error) {
	rows, err := db.QueryContext(ctx, riverMigrationGetAllAssumingMain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigrationGetAllAssumingMainRow
	for rows.Next() {
		var i RiverMigrationGetAllAssumingMainRow
		if err := rows.Scan(&i.CreatedAt, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationGetByLine = `-- name: RiverMigrationGetByLine :many
SELECT line, version, created_at
FROM /* TEMPLATE: schema */river_migration
WHERE line = ?1
ORDER BY version
`

func (q *Queries) RiverMigrationGetByLine(ctx context.Context, db DBTX, line string) ([]*RiverMigration, error) {
	rows, err := db.QueryContext(ctx, riverMigrationGetByLine, line)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigration
	for rows.Next() {
		var i RiverMigration
		if err := rows.Scan(&i.Line, &i.Version, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationInsertMany = `-- name: RiverMigrationInsertMany :many
INSERT INTO /* TEMPLATE: schema */river_migration (
    line,
    version
)
SELECT
    ?1,
    value
FROM json_each(cast(?2 AS blob))
RETURNING line, version, created_at
`

type RiverMigrationInsertManyParams struct {
	Line     string
	Versions []byte
}

func (q *Queries) RiverMigrationInsertMany(ctx context.Context, db DBTX, arg *RiverMigrationInsertManyParams) ([]*RiverMigration, error) {
	rows, err := db.QueryContext(ctx, riverMigrationInsertMany, arg.Line, arg.Versions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigration
	for rows.Next() {
		var i RiverMigration
		if err := rows.Scan(&i.Line, &i.Version, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riverMigrationInsertManyAssumingMain = `-- name: RiverMigrationInsertManyAssumingMain :many
INSERT INTO /* TEMPLATE: schema */river_migration (
    version
)
SELECT
    value
FROM json_each(cast(?1 AS blob))
RETURNING
    created_at,
    version
`

type RiverMigrationInsertManyAssumingMainRow struct {
	CreatedAt time.Time
	Version   int64
}

func (q *Queries) RiverMigrationInsertManyAssumingMain(ctx context.Context, db DBTX, versions []byte) ([]*RiverMigrationInsertManyAssumingMainRow, error) {
	rows, err := db.QueryContext(ctx, riverMigrationInsertManyAssumingMain, versions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RiverMigrationInsertManyAssumingMainRow
	for rows.Next() {
		var i RiverMigrationInsertManyAssumingMainRow
		if err := rows.Scan(&i.CreatedAt, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
