// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: river_notification.sql

package dbsqlc

import (
	"context"
)

const notificationDeleteBefore = `-- name: NotificationDeleteBefore :execrows
DELETE FROM /* TEMPLATE: schema */river_notification
WHERE created_at < cast(?1 AS text)
`

func (q *Queries) NotificationDeleteBefore(ctx context.Context, db DBTX, createdAtHorizon string) (int64, error) {
	result, err := db.ExecContext(ctx, notificationDeleteBefore, createdAtHorizon)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const notificationGetAfter = `-- name: NotificationGetAfter :one
SELECT id, created_at, payload, topic
FROM /* TEMPLATE: schema */river_notification
WHERE id > ?1
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) NotificationGetAfter(ctx context.Context, db DBTX, after int64) (*RiverNotification, error) {
	row := db.QueryRowContext(ctx, notificationGetAfter, after)
	var i RiverNotification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Payload,
		&i.Topic,
	)
	return &i, err
}

const notificationGetLastID = `-- name: NotificationGetLastID :one
SELECT cast(coalesce(max(id), 0) AS integer)
FROM /* TEMPLATE: schema */river_notification
`

func (q *Queries) NotificationGetLastID(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRowContext(ctx, notificationGetLastID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const notificationInsertMany = `-- name: NotificationInsertMany :exec
INSERT INTO /* TEMPLATE: schema */river_notification (
    payload,
    topic
)
SELECT
    json_extract(value, '$.payload'),
    json_extract(value, '$.topic')
FROM json_each(cast(?1 AS blob))
`

func (q *Queries) NotificationInsertMany(ctx context.Context, db DBTX, notifications []byte) error {
	_, err := db.ExecContext(ctx, notificationInsertMany, notifications)
	return err
}
