// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: schema.sql

package dbsqlc

import (
	"context"
)

const indexExists = `-- name: IndexExists :one
SELECT EXISTS (
    SELECT 1
    FROM /* TEMPLATE: schema */sqlite_master WHERE type = 'index' AND name = cast(?1 AS text)
)
`

func (q *Queries) IndexExists(ctx context.Context, db DBTX, index string) (int64, error) {
	row := db.QueryRowContext(ctx, indexExists, index)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const tableExists = `-- name: TableExists :one
SELECT EXISTS (
    SELECT 1
    FROM /* TEMPLATE: schema */sqlite_master WHERE type = 'table' AND name = cast(?1 AS text)
)
`

func (q *Queries) TableExists(ctx context.Context, db DBTX, table string) (int64, error) {
	row := db.QueryRowContext(ctx, tableExists, table)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
