[graph]
all-features = true

[advisories]
yanked = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]
confidence-threshold = 0.8

[bans]
highlight = "all"
multiple-versions = "warn"
wildcards = "allow"

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"
