[package]
name = "riverqueue-test"
description = "Test helpers for River's Rust client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["postgres"]
postgres = ["riverqueue/postgres"]
sqlite = ["riverqueue/sqlite"]

[dependencies]
chrono.workspace = true
riverqueue = { path = "../riverqueue", version = "=0.46.0-alpha.1", default-features = false }
serde_json.workspace = true
tokio-util.workspace = true

[dev-dependencies]
serde.workspace = true
tokio.workspace = true

[lints]
workspace = true
