package harness_test

const (
	scenarioOwnerInsertOnly             = "TestInsertOnlyConformance"
	scenarioOwnerMaintenance            = "TestMaintenanceConformance"
	scenarioOwnerMixed                  = "TestMixedConformance"
	scenarioOwnerMultiEngine            = "TestMultiEngineConformance"
	scenarioOwnerMultiEnginePerformance = "TestMultiEnginePerformanceGate"
	scenarioOwnerMultiEngineSQLite      = "TestMultiEngineSQLiteConformance"
	scenarioOwnerMultiEngineSoak        = "TestMultiEngineSoak"
	scenarioOwnerPerformance            = "TestPerformanceGate"
	scenarioOwnerResilience             = "TestResilienceConformance"
	scenarioOwnerSQLiteResilience       = "TestResilienceSQLiteConformance"
	scenarioOwnerSQLiteRuntime          = "TestMixedSQLiteRuntimeConformance"
	scenarioOwnerSQLiteStorage          = "TestMixedSQLiteConformance"
	scenarioOwnerSoak                   = "TestMixedSoak"
)

type scenarioBinding struct {
	owner   string
	profile string
	tier    string
}

// scenarioRegistry is the executable source of truth for conformance
// scenarios. Each owning test must report every bound scenario as passed before
// it returns successfully; artifact validation separately requires core.json to
// contain this exact set with matching tiers.
var scenarioRegistry = map[string]scenarioBinding{ //nolint:gochecknoglobals // shared executable catalog
	"adapter_handshake_and_capabilities":                             {owner: scenarioOwnerMixed, tier: "codec"},
	"barrier_wait_and_release":                                       {owner: scenarioOwnerMixed, tier: "runtime"},
	"bulk_delete_safety":                                             {owner: scenarioOwnerMixed, tier: "storage"},
	"candidate_insert_reference_work":                                {owner: scenarioOwnerMixed, tier: "mixed"},
	"candidate_migrator_reference_runtime":                           {owner: scenarioOwnerMixed, tier: "storage"},
	"candidate_process_kill_reference_rescue":                        {owner: scenarioOwnerMixed, tier: "chaos"},
	"claimed_row_decode_isolation":                                   {owner: scenarioOwnerResilience, tier: "mixed"},
	"clock_boundary_scheduling":                                      {owner: scenarioOwnerMixed, tier: "mixed"},
	"completion_batching":                                            {owner: scenarioOwnerMixed, tier: "performance"},
	"completion_row_lock_wait":                                       {owner: scenarioOwnerResilience, tier: "chaos"},
	"completion_transient_failure_retry":                             {owner: scenarioOwnerResilience, tier: "chaos"},
	"cooperative_remote_cancellation":                                {owner: scenarioOwnerMixed, tier: "runtime"},
	"cron_schedule_goldens":                                          {owner: scenarioOwnerMaintenance, tier: "codec"},
	"cross_language_unique_conflict":                                 {owner: scenarioOwnerMixed, tier: "codec"},
	"custom_schema_candidate_migrate_reference_work":                 {owner: scenarioOwnerMixed, tier: "mixed"},
	"custom_schema_reference_migrate_candidate_work":                 {owner: scenarioOwnerMixed, tier: "mixed"},
	"database_unavailable_reconnect":                                 {owner: scenarioOwnerResilience, tier: "chaos"},
	"default_retry_policy_schedule":                                  {owner: scenarioOwnerMixed, tier: "runtime"},
	"deterministic_retry_clock_rng":                                  {owner: scenarioOwnerMixed, tier: "codec"},
	"differential_job_crud":                                          {owner: scenarioOwnerMixed, tier: "storage"},
	"differential_job_list_filters_and_cursors":                      {owner: scenarioOwnerMixed, tier: "storage"},
	"differential_queue_crud":                                        {owner: scenarioOwnerMixed, tier: "storage"},
	"dynamic_queue_add_reconfigure_remove":                           {owner: scenarioOwnerMixed, tier: "runtime"},
	"error_handler_cancel_override":                                  {owner: scenarioOwnerMixed, tier: "runtime"},
	"extension_hook_middleware_order":                                {owner: scenarioOwnerMixed, tier: "runtime"},
	"external_terminal_completion_race":                              {owner: scenarioOwnerMixed, tier: "mixed"},
	"fast_insert_both_implementations":                               {owner: scenarioOwnerMixed, tier: "storage"},
	"hard_shutdown_soft_stop_classification":                         {owner: scenarioOwnerResilience, tier: "runtime"},
	"historical_migration_down_up":                                   {owner: scenarioOwnerMixed, tier: "storage"},
	"ignored_cancellation_hard_abort":                                {owner: scenarioOwnerMixed, tier: "chaos"},
	"job_row_round_trip_all_fields":                                  {owner: scenarioOwnerMixed, tier: "codec"},
	"leadership_renewal_under_slow_maintenance":                      {owner: scenarioOwnerMaintenance, tier: "runtime"},
	"leadership_same_client_id_term_replacement":                     {owner: scenarioOwnerMaintenance, tier: "runtime"},
	"listener_backend_disconnect_reconnect":                          {owner: scenarioOwnerMixed, tier: "chaos"},
	"lost_notification_poll_recovery":                                {owner: scenarioOwnerMixed, tier: "chaos"},
	"maintenance_job_cleaner_retention":                              {owner: scenarioOwnerMaintenance, tier: "runtime"},
	"maintenance_queue_cleaner_keeps_active_queues":                  {owner: scenarioOwnerMaintenance, tier: "runtime"},
	"maintenance_reindexer_skips_artifacts":                          {owner: scenarioOwnerMaintenance, tier: "runtime"},
	"maintenance_rescuer_full_batch_of_unexpired_jobs":               {owner: scenarioOwnerMaintenance, tier: "runtime"},
	"maintenance_rescuer_stale_selection":                            {owner: scenarioOwnerMaintenance, tier: "runtime"},
	"migration_mixed_case_schema":                                    {owner: scenarioOwnerMaintenance, tier: "storage"},
	"mixed_connection_pool_bound":                                    {owner: scenarioOwnerSoak, tier: "performance"},
	"mixed_leader_death_failover_both_directions":                    {owner: scenarioOwnerMixed, tier: "chaos"},
	"mixed_leader_failover_both_directions":                          {owner: scenarioOwnerMixed, tier: "mixed"},
	"mixed_request_resign_terms":                                     {owner: scenarioOwnerMixed, tier: "mixed"},
	"mixed_skip_locked_competition":                                  {owner: scenarioOwnerMixed, tier: "mixed"},
	"mixed_soak":                                                     {owner: scenarioOwnerSoak, tier: "performance"},
	"mixed_unknown_kind_error":                                       {owner: scenarioOwnerMixed, tier: "mixed"},
	"multi_engine_competition":                                       {owner: scenarioOwnerMultiEngine, tier: "mixed"},
	"multi_engine_directed_candidate_work_notification_cancellation": {owner: scenarioOwnerMultiEngine, tier: "mixed"},
	"multi_engine_fault_recovery":                                    {owner: scenarioOwnerMultiEngine, tier: "chaos"},
	"multi_engine_leader_failover":                                   {owner: scenarioOwnerMultiEngine, tier: "mixed"},
	"multi_engine_process_kill_rescue_failover":                      {owner: scenarioOwnerMultiEngine, tier: "chaos"},
	"multi_engine_release_performance":                               {owner: scenarioOwnerMultiEnginePerformance, tier: "performance"},
	"multi_engine_resource_bound":                                    {owner: scenarioOwnerMultiEngine, tier: "performance"},
	"multi_engine_resumable_cursor":                                  {owner: scenarioOwnerMultiEngine, tier: "mixed"},
	"multi_engine_soak":                                              {owner: scenarioOwnerMultiEngineSoak, tier: "performance"},
	"multi_engine_sqlite_candidate_pairs":                            {owner: scenarioOwnerMultiEngineSQLite, profile: "sqlite-runtime-v1", tier: "mixed"},
	"notification_only_wakeups":                                      {owner: scenarioOwnerMixed, tier: "mixed"},
	"panic_attempt_trace":                                            {owner: scenarioOwnerMixed, tier: "runtime"},
	"pause_resume_notification":                                      {owner: scenarioOwnerMixed, tier: "mixed"},
	"periodic_run_on_start":                                          {owner: scenarioOwnerMixed, tier: "runtime"},
	"pool_pressure_completion":                                       {owner: scenarioOwnerMixed, tier: "performance"},
	"process_kill_restart_and_rescue":                                {owner: scenarioOwnerMixed, tier: "chaos"},
	"queue_names_and_unknown_queue_control":                          {owner: scenarioOwnerMaintenance, tier: "storage"},
	"reference_insert_candidate_work":                                {owner: scenarioOwnerMixed, tier: "mixed"},
	"reference_migrator_candidate_runtime":                           {owner: scenarioOwnerMixed, tier: "storage"},
	"reference_process_kill_candidate_rescue":                        {owner: scenarioOwnerMixed, tier: "chaos"},
	"refetched_attempt_cancellation":                                 {owner: scenarioOwnerMixed, tier: "runtime"},
	"release_enqueue_performance":                                    {owner: scenarioOwnerPerformance, tier: "performance"},
	"release_mixed_performance":                                      {owner: scenarioOwnerPerformance, tier: "performance"},
	"release_worker_performance":                                     {owner: scenarioOwnerPerformance, tier: "performance"},
	"remote_cancel_notification":                                     {owner: scenarioOwnerMixed, tier: "mixed"},
	"remote_queue_subscription_events":                               {owner: scenarioOwnerMixed, tier: "mixed"},
	"reserved_metadata_cross_engine":                                 {owner: scenarioOwnerMixed, tier: "mixed"},
	"resumable_cross_engine_cursor":                                  {owner: scenarioOwnerMixed, tier: "mixed"},
	"resumable_retry":                                                {owner: scenarioOwnerMixed, tier: "runtime"},
	"resumable_validation":                                           {owner: scenarioOwnerMixed, tier: "runtime"},
	"multi_engine_sqlite_candidate_pairs":                            {owner: scenarioOwnerMultiEngineSQLite, profile: "sqlite-runtime-v1", tier: "mixed"},
	"rolling_deployment_same_protocol":                               {owner: scenarioOwnerMixed, tier: "mixed"},
	"shutdown_after_cancel_attempt":                                  {owner: scenarioOwnerResilience, tier: "runtime"},
	"single_implementation_worker_outcomes":                          {owner: scenarioOwnerMixed, tier: "runtime"},
	"snooze_once_metadata_transition":                                {owner: scenarioOwnerMixed, tier: "runtime"},
	"stuck_job_detection":                                            {owner: scenarioOwnerMixed, tier: "runtime"},
	"timeout_cancellation":                                           {owner: scenarioOwnerMixed, tier: "runtime"},
	"transaction_abort_rollback_visibility":                          {owner: scenarioOwnerMixed, tier: "storage"},
	"transaction_commit_visibility":                                  {owner: scenarioOwnerMixed, tier: "storage"},
	"transaction_rollback_visibility":                                {owner: scenarioOwnerMixed, tier: "storage"},
	"transactional_batch_insertion":                                  {owner: scenarioOwnerMixed, tier: "storage"},
	"transactional_completion":                                       {owner: scenarioOwnerMixed, tier: "storage"},
	"transactional_cross_language_cancel":                            {owner: scenarioOwnerMixed, tier: "mixed"},
	"transactional_crud_commit_rollback":                             {owner: scenarioOwnerMixed, tier: "storage"},
	"transactional_fast_batch_insertion":                             {owner: scenarioOwnerMixed, tier: "storage"},
	"transactional_insert_notification_commit_only":                  {owner: scenarioOwnerMixed, tier: "mixed"},
	"transactional_queue_operations":                                 {owner: scenarioOwnerMixed, tier: "storage"},
	"typed_batch_insertion":                                          {owner: scenarioOwnerMixed, tier: "storage"},
	"unique_hash_goldens":                                            {owner: scenarioOwnerMixed, tier: "codec"},
	"unsafe_int64_job_ids_rpc_list_cursors":                          {owner: scenarioOwnerMixed, tier: "codec"},
	"insert_only_insert_notification":                                {owner: scenarioOwnerInsertOnly, profile: "insert-only-v1", tier: "mixed"},
	"insert_only_insert_reference_work":                              {owner: scenarioOwnerInsertOnly, profile: "insert-only-v1", tier: "mixed"},
	"insert_only_profile_handshake":                                  {owner: scenarioOwnerInsertOnly, profile: "insert-only-v1", tier: "codec"},
	"insert_only_transactional_insert":                               {owner: scenarioOwnerInsertOnly, profile: "insert-only-v1", tier: "storage"},
	"insert_only_typed_batch":                                        {owner: scenarioOwnerInsertOnly, profile: "insert-only-v1", tier: "storage"},
	"insert_only_unique_insert":                                      {owner: scenarioOwnerInsertOnly, profile: "insert-only-v1", tier: "codec"},
	"multi_engine_sqlite_candidate_pairs":                            {owner: scenarioOwnerMultiEngineSQLite, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_batch_atomicity":                                         {owner: scenarioOwnerSQLiteStorage, profile: "portable-storage-v1", tier: "storage"},
	"sqlite_deterministic_retry_unique":                              {owner: scenarioOwnerSQLiteStorage, profile: "portable-storage-v1", tier: "codec"},
	"sqlite_insert_get_unique_cross_language":                        {owner: scenarioOwnerSQLiteStorage, profile: "portable-storage-v1", tier: "mixed"},
	"sqlite_job_crud":                                                {owner: scenarioOwnerSQLiteStorage, profile: "portable-storage-v1", tier: "storage"},
	"sqlite_migration_cross_language":                                {owner: scenarioOwnerSQLiteStorage, profile: "portable-storage-v1", tier: "storage"},
	"sqlite_profile_handshake":                                       {owner: scenarioOwnerSQLiteStorage, profile: "portable-storage-v1", tier: "codec"},
	"sqlite_runtime_attempted_by_ordering":                           {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_competing_workers":                               {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_completion_under_writer_lock":                    {owner: scenarioOwnerSQLiteResilience, profile: "sqlite-runtime-v1", tier: "chaos"},
	"sqlite_runtime_cross_language_work":                             {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_extensions_resumable_subscriptions":              {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "runtime"},
	"sqlite_runtime_external_terminal_completion_race":               {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_go_integer_ranges":                               {owner: scenarioOwnerSQLiteResilience, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_leadership_failover":                             {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "runtime"},
	"sqlite_runtime_lifecycle_shutdown":                              {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "runtime"},
	"sqlite_runtime_notification_wakeups":                            {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_periodic_scheduler":                              {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "runtime"},
	"sqlite_runtime_poll_only_recovery":                              {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "runtime"},
	"sqlite_runtime_profile_handshake":                               {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "codec"},
	"sqlite_runtime_queue_crud_reconfigure_pause":                    {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_remote_cancellation":                             {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_remote_queue_subscription_events":                {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_resumable_cross_engine_cursor":                   {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_resumable_validation":                            {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "runtime"},
	"sqlite_runtime_transactional_notification":                      {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_runtime_unknown_kind_error":                              {owner: scenarioOwnerSQLiteRuntime, profile: "sqlite-runtime-v1", tier: "mixed"},
	"sqlite_timestamp_rounding_ordering":                             {owner: scenarioOwnerSQLiteStorage, profile: "portable-storage-v1", tier: "codec"},
	"sqlite_transactions":                                            {owner: scenarioOwnerSQLiteStorage, profile: "portable-storage-v1", tier: "storage"},
	"sqlite_unsafe_int64_job_ids_rpc_list_cursors":                   {owner: scenarioOwnerSQLiteStorage, profile: "portable-storage-v1", tier: "codec"},
	"timeout_cancellation":                                           {owner: scenarioOwnerMixed, tier: "runtime"},
	"transaction_abort_rollback_visibility":                          {owner: scenarioOwnerMixed, tier: "storage"},
	"transaction_commit_visibility":                                  {owner: scenarioOwnerMixed, tier: "storage"},
	"transaction_rollback_visibility":                                {owner: scenarioOwnerMixed, tier: "storage"},
	"transactional_batch_insertion":                                  {owner: scenarioOwnerMixed, tier: "storage"},
	"transactional_completion":                                       {owner: scenarioOwnerMixed, tier: "storage"},
	"transactional_cross_language_cancel":                            {owner: scenarioOwnerMixed, tier: "mixed"},
	"transactional_crud_commit_rollback":                             {owner: scenarioOwnerMixed, tier: "storage"},
	"transactional_fast_batch_insertion":                             {owner: scenarioOwnerMixed, tier: "storage"},
	"transactional_insert_notification_commit_only":                  {owner: scenarioOwnerMixed, tier: "mixed"},
	"transactional_queue_operations":                                 {owner: scenarioOwnerMixed, tier: "storage"},
	"typed_batch_insertion":                                          {owner: scenarioOwnerMixed, tier: "storage"},
	"unique_hash_goldens":                                            {owner: scenarioOwnerMixed, tier: "codec"},
	"unsafe_int64_job_ids_rpc_list_cursors":                          {owner: scenarioOwnerMixed, tier: "codec"},
}
